/* GPMF MAIN CONTROLLER - V3.0 (FINAL) */

const translations = {
    es: {
        // MENÚ
        "nav.home": "Inicio",
        "nav.firm": "Firma",
        "nav.services": "Servicios",
        "nav.contact": "Agendar",
        "nav.int": "Internacionalización",
        "nav.data": "Datos e IA",
        "nav.ai": "IA & Analítica",
        "nav.bizdev": "Expansión & Soluciones Sectoriales",
        "nav.partners": "Aliados",
        "nav.team": "Equipo",

        // HOME - HERO
        "home.hero.title": "Navegando la complejidad global a través de",
        "home.hero.span": "inteligencia estratégica.",
        "home.hero.desc": "Ayudamos a organizaciones a prosperar en ecosistemas complejos mediante gestión multidisciplinaria, intercultural y transformación basada en datos.",
        "home.hero.cta": "Hablemos de su Estrategia",
        "home.hero.services": "Explorar Servicios",
        "home.trust.title": "Confianza generada en ecosistemas globales",

        // HOME - PROPUESTA VALOR (ICONOS)
        "home.prop.title": "Nuestra Diferencia",
        "home.prop.1.title": "Conexión Global",
        "home.prop.1.desc": "Puentes reales entre ecosistemas de LatAm y Europa.",
        "home.prop.2.title": "Enfoque Colaborativo",
        "home.prop.2.desc": "Co-creamos soluciones, no imponemos respuestas.",
        "home.prop.3.title": "Innovación Continua",
        "home.prop.3.desc": "Tecnología y datos al servicio de la estrategia humana.",

        // HOME - AREAS
        "home.areas.title": "Áreas de Práctica",
        "home.areas.desc": "Unimos estrategia, gestión inteligente de datos y formación interdisciplinaria.",
        "home.services.card1.title": "Internacionalización",
        "home.services.card1.desc": "Expansión con enfoque intercultural. Desde benchmarking hasta softlanding operativo.",
        "home.services.card1.bullet1": "Alianzas Estratégicas",
        "home.services.card1.bullet2": "Misiones Comerciales",
        "home.services.card2.title": "Gobernanza de Datos",
        "home.services.card2.desc": "Convertimos datos dispersos en activos estratégicos para decisiones informadas.",
        "home.services.card2.bullet1": "Diagnóstico de Madurez",
        "home.services.card2.bullet2": "Arquitectura de Datos",
        "home.services.card3.title": "Gestión Intercultural",
        "home.services.card3.desc": "Fortalecimiento de capacidades internas, liderazgo y cultura organizacional.",
        "home.services.card3.bullet1": "Entrenamiento Equipos",
        "home.services.card3.bullet2": "Planeación Estratégica",
        "home.services.card4.title": "Expansión & Soluciones Sectoriales",
        "home.services.card4.desc": "Expansión, alianzas y soluciones a medida para Agro-Tech, Ciencia y Construcción.",
        "home.services.card4.bullet1": "Diagnóstico + roadmap internacional",
        "home.services.card4.bullet2": "Red global y cierre de alianzas",
        "common.viewDetails": "Ver detalles →",

        // HOME - WHY
        "home.why.title": "No traemos respuestas enlatadas.",
        "home.why.span": "Co-creamos soluciones.",
        "home.why.desc": "En un mundo saturado de información, el valor no está en los datos, sino en la capacidad de transformarlos en acción.",
        "home.why.pillar1.title": "Rigurosidad Metodológica",
        "home.why.pillar1.desc": "Procesos estandarizados validados en Europa y Latam.",
        "home.why.pillar2.title": "Agilidad Boutique",
        "home.why.pillar2.desc": "Atención directa de socias senior, sin burocracia.",
        "home.why.pillar3.title": "Visión Global",
        "home.why.pillar3.desc": "ADN trilingüe y multicultural nativo.",
        "home.testimonial.quote": "GPMF entendió nuestra complejidad técnica y la tradujo en una estrategia de expansión clara y ejecutable. No solo nos dieron un plan, nos ayudaron a construir la capacidad para ejecutarlo.",
        "home.testimonial.person": "David A. Rachid",
        "home.testimonial.role": "CEO, DCR Exponential (USA)",
        "home.cta.title": "Listo para elevar el estándar.",
        "home.cta.desc": "Agende una sesión de diagnóstico estratégico de 30 minutos sin costo.",
        "home.cta.btn.primary": "Solicitar Diagnóstico",
        "home.cta.btn.secondary": "WhatsApp Directo",

        // ABOUT
        "about.hero.title": "Ciencia y Estrategia.",
        "about.hero.subtitle": "Sin fronteras.",
        "about.hero.desc": "GPMF no es una consultora tradicional. Somos un híbrido entre la rigurosidad de la ingeniería y la agilidad de los negocios globales.",
        "about.team.title": "Liderazgo Senior",
        "about.team.desc": "Atención directa de las socias. Sin intermediarios junior.",
        "about.team.adriana.role": "Ingeniería & Complejidad",
        "about.team.adriana.desc": "Ingeniera con amplia trayectoria en R&D, políticas públicas y sistemas complejos (INRAE, Colciencias). Aporta estructura sistémica y credibilidad técnica.",
        "about.team.marcela.role": "Estrategia & Expansión",
        "about.team.marcela.desc": "Experta en desarrollo de negocios y M&A Sourcing con visión trilingüe (ES/EN/DE). Abre mercados complejos y negociaciones B2B/B2G de alto ticket.",
        "about.vision.title": "Nuestra Estrella Norte",
        "about.vision.desc": "Para 2030, seremos la firma boutique de referencia que conecta Latinoamérica, Europa y Norteamérica.",
        "about.vision.quote": "Para 2030, seremos la firma boutique de referencia que conecta Latinoamérica, Europa y Norteamérica, transformando la diversidad cultural y tecnológica en ventaja competitiva.",
        "about.vision.stat1": "Continentes",
        "about.vision.stat2": "Años Exp. Conjunta",
        "about.vision.stat3": "Atención Senior",

        // ALLIES PAGE
        "allies.hero.kicker": "Red Global",
        "allies.hero.title": "Personas y Firmas que amplifican nuestro impacto",
        "allies.hero.desc": "Unimos liderazgo senior, estrategas especializados y aliados institucionales en Europa, Norteamérica y Latinoamérica para desbloquear proyectos complejos.",
        "allies.core.kicker": "Core Team",
        "allies.core.title": "Socias y directores de práctica",
        "allies.core.subtitle": "Atención directa, sin intermediarios junior",
        "allies.core.marcela.role": "Network Management",
        "allies.core.marcela.desc": "Transformación digital y expansión comercial en ecosistemas trinlingües ES/EN/DE.",
        "allies.core.adriana.role": "Innovation & Políticas Públicas",
        "allies.core.adriana.desc": "Ingeniera y estratega en ciencia, agro e inteligencia competitiva para gobiernos y multilaterales.",
        "allies.core.natalia.role": "Análisis & Operaciones",
        "allies.core.natalia.desc": "Diseño de operaciones internas y analítica aplicada para escalabilidad organizacional.",
        "allies.core.carlos.role": "Business Intelligence & IA",
        "allies.core.carlos.desc": "12+ años en BI, data strategy y despliegues de IA para corporaciones LatAm-Europa.",
        "allies.partners.kicker": "Alianzas",
        "allies.partners.title": "Partners y firmas asociadas",
        "allies.partners.subtitle": "Células especializadas que extendemos según el proyecto",
        "allies.partner.atelier.desc": "Think tank en transición energética, diplomacia climática y financiamiento verde.",
        "allies.partner.atelier.point1": "• Diseño de hojas de ruta Net-Zero",
        "allies.partner.atelier.point2": "• Coordinación con instituciones UE",
        "allies.partner.nordic.desc": "Estudio boutique en softlanding legal y comercial para scaleups tecnológicas.",
        "allies.partner.nordic.point1": "• Estructuración societaria UE",
        "allies.partner.nordic.point2": "• Acceso a fondos y hubs digitales",
        "allies.partner.agro.desc": "Red de expertos en bioeconomía, agrotech y transferencia tecnológica.",
        "allies.partner.agro.point1": "• Proyectos de cooperación internacional",
        "allies.partner.agro.point2": "• Inteligencia competitiva sectorial",
        "allies.partner.lumen.desc": "Laboratorio de IA aplicada en retail, salud y manufactura avanzada.",
        "allies.partner.lumen.point1": "• Desarrollo de modelos predictivos",
        "allies.partner.lumen.point2": "• Integración de datos multi-fuente",
        "allies.partner.andino.desc": "Colectivo de ex diplomáticos y negociadores B2G para proyectos de infraestructura.",
        "allies.partner.andino.point1": "• Relacionamiento institucional",
        "allies.partner.andino.point2": "• Gestión regulatoria",
        "allies.partner.humboldt.desc": "Spin-off académico que conecta universidades DACH con startups latinoamericanas.",
        "allies.partner.humboldt.point1": "• Programas de innovación abierta",
        "allies.partner.humboldt.point2": "• Transferencia tecnológica",
        "allies.cta.kicker": "Colaboración Extendida",
        "allies.cta.title": "Una red viva para proyectos de alto riesgo y alto impacto.",
        "allies.cta.desc": "Activamos squads según el reto: data scientists, expertos legales, diplomáticos científicos, storytellers estratégicos. Todo integrado bajo el mismo playbook.",
        "allies.cta.point1": "Equipos transnacionales coordinados en tres zonas horarias.",
        "allies.cta.point2": "Contratos flexibles: pod, retainer o aceleración por sprint.",
        "allies.cta.point3": "Due diligence cultural y técnica antes de cada partnership.",
        "allies.cta.join.title": "¿Quieres sumarte como aliado?",
        "allies.cta.join.desc": "Buscamos firmas y profesionales con ADN boutique y enfoque en resultados. Ciencia, tecnología, data, diplomacia y expansión.",
        "allies.cta.join.btn.primary": "Postular alianza",
        "allies.cta.join.btn.secondary": "Agendar conversación",

        // CONTACT
        "contact.sidebar.title": "Conversemos",
        "contact.sidebar.desc": "Estamos listos para escuchar sus desafíos y explorar cómo nuestra red global puede acelerar sus resultados.",
        "contact.sidebar.email.label": "Email",
        "contact.sidebar.email.value": "contacto.gpmfsas@gmail.com",
        "contact.sidebar.location.label": "Ubicación",
        "contact.sidebar.location.city": "Bogotá, Colombia",
        "contact.sidebar.location.note": "Operaciones Globales",
        "contact.form.title": "Envíenos un mensaje",
        "contact.form.name": "Nombre",
        "contact.form.placeholder.name": "Su nombre",
        "contact.form.company": "Empresa",
        "contact.form.placeholder.company": "Su organización",
        "contact.form.email": "Email Corporativo",
        "contact.form.placeholder.email": "ejemplo@empresa.com",
        "contact.form.message": "Mensaje",
        "contact.form.placeholder.message": "¿Cómo podemos ayudarle?",
        "contact.form.submit": "Enviar Mensaje",
        "nav.contact": "Agendar",

        // COOKIES
        "cookie.text": "Utilizamos cookies para mejorar su experiencia.",
        "cookie.btn": "Aceptar"
    },
    en: {
        "nav.home": "Home",
        "nav.firm": "Firm",
        "nav.services": "Services",
        "nav.contact": "Book Now",
        "nav.int": "Internationalization",
        "nav.data": "Data & AI",
        "nav.ai": "AI & Analytics",
        "nav.bizdev": "Expansion & Sector Solutions",
        "nav.partners": "Allies",
        "nav.team": "Team",

        "home.hero.title": "Navigating global complexity through",
        "home.hero.span": "strategic intelligence.",
        "home.hero.desc": "We help organizations thrive in complex ecosystems through multidisciplinary management, intercultural expertise, and data-driven transformation.",
        "home.hero.cta": "Let's Discuss Strategy",
        "home.hero.services": "Explore Services",
        "home.trust.title": "Trusted across global ecosystems",

        "home.prop.title": "Our Difference",
        "home.prop.1.title": "Global Connection",
        "home.prop.1.desc": "Real bridges between LatAm and European ecosystems.",
        "home.prop.2.title": "Collaborative Approach",
        "home.prop.2.desc": "We co-create solutions, we don't impose answers.",
        "home.prop.3.title": "Continuous Innovation",
        "home.prop.3.desc": "Technology and data at the service of human strategy.",

        "home.areas.title": "Practice Areas",
        "home.areas.desc": "We unite strategy, intelligent data management, and interdisciplinary training.",
        "home.services.card1.title": "Internationalization",
        "home.services.card1.desc": "Expansion with an intercultural focus. From benchmarking to operational softlanding.",
        "home.services.card1.bullet1": "Strategic Alliances",
        "home.services.card1.bullet2": "Trade Missions",
        "home.services.card2.title": "Data Governance",
        "home.services.card2.desc": "We turn scattered data into strategic assets for informed decisions.",
        "home.services.card2.bullet1": "Maturity Assessment",
        "home.services.card2.bullet2": "Data Architecture",
        "home.services.card3.title": "Intercultural Management",
        "home.services.card3.desc": "Strengthening internal capabilities, leadership, and organizational culture.",
        "home.services.card3.bullet1": "Team Training",
        "home.services.card3.bullet2": "Strategic Planning",
        "home.services.card4.title": "Expansion & Sector Solutions",
        "home.services.card4.desc": "Expansion, alliances, and tailored plays for Agro-Tech, Science, and Construction.",
        "home.services.card4.bullet1": "Opportunity diagnostic & global roadmap",
        "home.services.card4.bullet2": "Partnership activation & deal support",
        "common.viewDetails": "View details →",
        
        "home.why.title": "No canned answers.",
        "home.why.span": "We co-create solutions.",
        "home.why.desc": "In an information-saturated world, value lies not in data, but in the ability to transform it into action.",
        "home.why.pillar1.title": "Methodological Rigor",
        "home.why.pillar1.desc": "Standardized processes validated in Europe and LatAm.",
        "home.why.pillar2.title": "Boutique Agility",
        "home.why.pillar2.desc": "Direct senior partner attention, zero bureaucracy.",
        "home.why.pillar3.title": "Global Vision",
        "home.why.pillar3.desc": "Native trilingual and multicultural DNA.",
        "home.testimonial.quote": "GPMF understood our technical complexity and turned it into a clear, executable expansion strategy. They didn’t just deliver a plan—they helped us build the capacity to execute it.",
        "home.testimonial.person": "David A. Rachid",
        "home.testimonial.role": "CEO, DCR Exponential (USA)",
        "home.cta.title": "Ready to raise the standard.",
        "home.cta.desc": "Book a complimentary 30-minute strategic diagnostic session.",
        "home.cta.btn.primary": "Request Diagnostic",
        "home.cta.btn.secondary": "Direct WhatsApp",

        "about.hero.title": "Science and Strategy.",
        "about.hero.subtitle": "Borderless.",
        "about.hero.desc": "GPMF is not a traditional consulting firm. We are a hybrid between engineering rigor and global business agility.",
        "about.team.title": "Senior Leadership",
        "about.team.desc": "Direct attention from partners. No junior intermediaries.",
        "about.team.adriana.role": "Engineering & Complexity",
        "about.team.adriana.desc": "Engineer with extensive experience in R&D, public policy, and complex systems (INRAE, Colciencias). Brings systemic structure and technical credibility.",
        "about.team.marcela.role": "Strategy & Expansion",
        "about.team.marcela.desc": "Expert in Business Development and M&A sourcing with trilingual vision (ES/EN/DE). Opens difficult markets and high-ticket B2B/B2G negotiations.",
        "about.vision.title": "Our North Star",
        "about.vision.desc": "By 2030, we will be the boutique firm of reference connecting Latin America, Europe, and North America.",
        "about.vision.quote": "By 2030, we will be the boutique firm of reference connecting Latin America, Europe, and North America, turning cultural and technological diversity into a competitive edge.",
        "about.vision.stat1": "Continents",
        "about.vision.stat2": "Years Combined Experience",
        "about.vision.stat3": "Senior Attention",
        
        "allies.hero.kicker": "Global Network",
        "allies.hero.title": "People and Firms that amplify our impact",
        "allies.hero.desc": "We bring together senior leadership, specialized strategists, and institutional allies across Europe, North America, and Latin America to unlock complex projects.",
        "allies.core.kicker": "Core Team",
        "allies.core.title": "Partners and practice directors",
        "allies.core.subtitle": "Direct attention, no junior intermediaries",
        "allies.core.marcela.role": "Network Management",
        "allies.core.marcela.desc": "Digital transformation and business expansion across trilingual ES/EN/DE ecosystems.",
        "allies.core.adriana.role": "Innovation & Public Policy",
        "allies.core.adriana.desc": "Engineer and strategist in science, agro, and competitive intelligence for governments and multilaterals.",
        "allies.core.natalia.role": "Analytics & Operations",
        "allies.core.natalia.desc": "Design of internal operations and applied analytics for organizational scalability.",
        "allies.core.carlos.role": "Business Intelligence & AI",
        "allies.core.carlos.desc": "12+ years in BI, data strategy, and AI deployments for LatAm–Europe corporations.",
        "allies.partners.kicker": "Alliances",
        "allies.partners.title": "Partner firms and associates",
        "allies.partners.subtitle": "Specialized cells we deploy per project",
        "allies.partner.atelier.desc": "Think tank in energy transition, climate diplomacy, and green finance.",
        "allies.partner.atelier.point1": "• Net-zero roadmap design",
        "allies.partner.atelier.point2": "• Coordination with EU institutions",
        "allies.partner.nordic.desc": "Boutique studio for legal and commercial softlanding of tech scaleups.",
        "allies.partner.nordic.point1": "• EU corporate structuring",
        "allies.partner.nordic.point2": "• Access to funds and digital hubs",
        "allies.partner.agro.desc": "Network of experts in bioeconomy, agrotech, and technology transfer.",
        "allies.partner.agro.point1": "• International cooperation projects",
        "allies.partner.agro.point2": "• Sector competitive intelligence",
        "allies.partner.lumen.desc": "AI applied lab for retail, health, and advanced manufacturing.",
        "allies.partner.lumen.point1": "• Predictive model development",
        "allies.partner.lumen.point2": "• Multi-source data integration",
        "allies.partner.andino.desc": "Collective of former diplomats and B2G negotiators for infrastructure projects.",
        "allies.partner.andino.point1": "• Institutional relationship management",
        "allies.partner.andino.point2": "• Regulatory management",
        "allies.partner.humboldt.desc": "Academic spin-off connecting DACH universities with Latin American startups.",
        "allies.partner.humboldt.point1": "• Open innovation programs",
        "allies.partner.humboldt.point2": "• Technology transfer",
        "allies.cta.kicker": "Extended Collaboration",
        "allies.cta.title": "A living network for high-risk, high-impact projects.",
        "allies.cta.desc": "We activate squads per challenge: data scientists, legal experts, science diplomats, strategic storytellers.",
        "allies.cta.point1": "Transnational teams coordinated across three time zones.",
        "allies.cta.point2": "Flexible contracts: pod, retainer, or sprint acceleration.",
        "allies.cta.point3": "Cultural and technical due diligence before every partnership.",
        "allies.cta.join.title": "Want to join as an ally?",
        "allies.cta.join.desc": "We look for boutique DNA firms focused on outcomes. Science, technology, data, diplomacy, and expansion.",
        "allies.cta.join.btn.primary": "Apply partnership",
        "allies.cta.join.btn.secondary": "Book a conversation",
        
        // CONTACT
        "contact.sidebar.title": "Let's connect",
        "contact.sidebar.desc": "We're ready to listen to your challenges and explore how our global network can accelerate your results.",
        "contact.sidebar.email.label": "Email",
        "contact.sidebar.email.value": "contacto.gpmfsas@gmail.com",
        "contact.sidebar.location.label": "Location",
        "contact.sidebar.location.city": "Bogotá, Colombia",
        "contact.sidebar.location.note": "Global operations",
        "contact.form.title": "Send us a message",
        "contact.form.name": "Name",
        "contact.form.placeholder.name": "Your name",
        "contact.form.company": "Company",
        "contact.form.placeholder.company": "Your organization",
        "contact.form.email": "Corporate Email",
        "contact.form.placeholder.email": "example@company.com",
        "contact.form.message": "Message",
        "contact.form.placeholder.message": "How can we help?",
        "contact.form.submit": "Send Message",
        "nav.contact": "Book Now",

        // COOKIES
        "cookie.text": "We use cookies to improve your experience.",
        "cookie.btn": "Accept"
    },
    de: {
        "nav.home": "Startseite",
        "nav.firm": "Firma",
        "nav.services": "Dienstleistungen",
        "nav.contact": "Buchen",
        "nav.int": "Internationalisierung",
        "nav.data": "Daten & KI",
        "nav.ai": "KI & Analytik",
        "nav.bizdev": "Expansion & Branchenlösungen",
        "nav.partners": "Partner",
        "nav.team": "Team",

        "home.hero.title": "Globale Komplexität meistern durch",
        "home.hero.span": "strategische Intelligenz.",
        "home.hero.desc": "Wir unterstützen Organisationen dabei, in komplexen Ökosystemen erfolgreich zu sein.",
        "home.hero.cta": "Strategie besprechen",
        "home.hero.services": "Dienstleistungen",
        "home.trust.title": "Vertrauen in globalen Ökosystemen",

        "home.prop.title": "Unser Unterschied",
        "home.prop.1.title": "Globale Verbindung",
        "home.prop.1.desc": "Echte Brücken zwischen LatAm und Europa.",
        "home.prop.2.title": "Kollaborativer Ansatz",
        "home.prop.2.desc": "Wir schaffen Lösungen gemeinsam.",
        "home.prop.3.title": "Kontinuierliche Innovation",
        "home.prop.3.desc": "La technologie au service de la stratégie.",

        "home.areas.title": "Kompetenzfelder",
        "home.areas.desc": "Strategie, Datenmanagement und interdisziplinäre Ausbildung.",
        "home.services.card1.title": "Internationalisierung",
        "home.services.card1.desc": "Expansion mit interkulturellem Fokus. Von Benchmarking bis zum operativen Softlanding.",
        "home.services.card1.bullet1": "Strategische Allianzen",
        "home.services.card1.bullet2": "Handelsmissionen",
        "home.services.card2.title": "Data Governance",
        "home.services.card2.desc": "Wir verwandeln verstreute Daten in strategische Assets für fundierte Entscheidungen.",
        "home.services.card2.bullet1": "Reifegrad-Diagnose",
        "home.services.card2.bullet2": "Datenarchitektur",
        "home.services.card3.title": "Interkulturelles Management",
        "home.services.card3.desc": "Stärkung interner Fähigkeiten, Leadership und Organisationskultur.",
        "home.services.card3.bullet1": "Team-Trainings",
        "home.services.card3.bullet2": "Strategische Planung",
        "home.services.card4.title": "Expansion & Branchenlösungen",
        "home.services.card4.desc": "Expansion, Allianzen und maßgeschneiderte Plays für Agro-Tech, Wissenschaft und Bauwesen.",
        "home.services.card4.bullet1": "Opportunity-Diagnose & globaler Fahrplan",
        "home.services.card4.bullet2": "Partnerschaftsaktivierung & Deal-Support",
        "common.viewDetails": "Details ansehen →",
        
        "home.why.title": "Keine Standardantworten.",
        "home.why.span": "Wir schaffen Lösungen.",
        "home.why.desc": "Der Wert liegt nicht in den Daten, sondern in der Fähigkeit, sie in Handlungen umzusetzen.",
        "home.why.pillar1.title": "Methodische Strenge",
        "home.why.pillar1.desc": "Standardisierte Prozesse, validiert in Europa und LatAm.",
        "home.why.pillar2.title": "Boutique-Agilität",
        "home.why.pillar2.desc": "Direkter Senior-Partner-Fokus, keine Bürokratie.",
        "home.why.pillar3.title": "Globale Vision",
        "home.why.pillar3.desc": "Trilinguales, multikulturelles ADN.",
        "home.testimonial.quote": "GPMF verstand unsere technische Komplexität und übersetzte sie in eine klare, ausführbare Expansionsstrategie. Sie lieferten nicht nur einen Plan, sie halfen uns auch bei der Umsetzung.",
        "home.testimonial.person": "David A. Rachid",
        "home.testimonial.role": "CEO, DCR Exponential (USA)",
        "home.cta.title": "Bereit, den Standard zu erhöhen.",
        "home.cta.desc": "Buchen Sie ein kostenloses, 30-minütiges Strategiegespräch.",
        "home.cta.btn.primary": "Diagnose anfragen",
        "home.cta.btn.secondary": "Direkt per WhatsApp",

        "about.hero.title": "Wissenschaft und Strategie.",
        "about.hero.subtitle": "Ohne Grenzen.",
        "about.hero.desc": "GPMF ist eine Mischung aus technischer Strenge und globaler Geschäftsagilität.",
        "about.team.title": "Senior Führung",
        "about.team.desc": "Direkte Betreuung durch Partner.",
        "about.team.adriana.role": "Ingénieurwesen & Komplexität",
        "about.team.adriana.desc": "Ingenieurin mit großer Erfahrung in F&E, öffentlichen Politiken und komplexen Systemen. Bringt Struktur und technische Glaubwürdigkeit.",
        "about.team.marcela.role": "Strategie & Expansion",
        "about.team.marcela.desc": "Experte in Business Development und M&A Sourcing mit trilingualer Sicht. Öffnet anspruchsvolle Märkte und B2B/B2G-Deals.",
        "about.vision.title": "Unser Polarstern",
        "about.vision.desc": "Bis 2030 werden wir die Referenz-Boutique sein, die LatAm, Europa und Nordamerika verbindet.",
        "about.vision.quote": "Bis 2030 sind wir die Boutique-Referenz zwischen Lateinamerika, Europa und Nordamerika, transformieren die Vielfalt und machen sie zur größten Stärke unserer Kunden.",
        "about.vision.stat1": "Kontinente",
        "about.vision.stat2": "Jahre gemeinsame Erfahrung",
        "about.vision.stat3": "Senior-Betreuung",
        
        "allies.hero.kicker": "Globales Netzwerk",
        "allies.hero.title": "Menschen und Firmen, die unseren Impact verstärken",
        "allies.hero.desc": "Wir vereinen Senior Leadership, Spezialisten und institutionelle Partner in Europa, Nordamerika und Lateinamerika für komplexe Projekte.",
        "allies.core.kicker": "Core Team",
        "allies.core.title": "Partnerinnen und Praxisdirektoren",
        "allies.core.subtitle": "Direkte Betreuung, ohne Junior-Zwischenschritte",
        "allies.core.marcela.role": "Network Management",
        "allies.core.marcela.desc": "Digitale Transformation und Geschäftsausbau in trilingualen ES/EN/DE-Ökosystemen.",
        "allies.core.adriana.role": "Innovation & öffentliche Politik",
        "allies.core.adriana.desc": "Ingenieurin und Strategin für Wissenschaft, Agro und Competitive Intelligence für Regierungen und Multilaterale.",
        "allies.core.natalia.role": "Analyse & Operationen",
        "allies.core.natalia.desc": "Design interner Abläufe und angewandte Analytik für Skalierung.",
        "allies.core.carlos.role": "Business Intelligence & KI",
        "allies.core.carlos.desc": "12+ Jahre BI, Datenstrategie und KI-Rollouts zwischen LatAm und Europa.",
        "allies.partners.kicker": "Partnerschaften",
        "allies.partners.title": "Partnerfirmen und Verbündete",
        "allies.partners.subtitle": "Spezialisierte Zellen je nach Projekt",
        "allies.partner.atelier.desc": "Think Tank für Energiewende, Klimadiplomatie und grüne Finanzierung.",
        "allies.partner.atelier.point1": "• Net-Zero-Fahrpläne",
        "allies.partner.atelier.point2": "• Koordination mit EU-Institutionen",
        "allies.partner.nordic.desc": "Boutique-Studio für legale und kommerzielle Softlanding von Tech-Scaleups.",
        "allies.partner.nordic.point1": "• EU-Gesellschaftsstruktur",
        "allies.partner.nordic.point2": "• Zugang zu Fonds und Digital-Hubs",
        "allies.partner.agro.desc": "Expertennetz für Bioökonomie, Agrotech und Technologietransfer.",
        "allies.partner.agro.point1": "• Internationale Kooperationsprojekte",
        "allies.partner.agro.point2": "• Sektorale Competitive Intelligence",
        "allies.partner.lumen.desc": "KI-Labor für Retail, Gesundheit und Advanced Manufacturing.",
        "allies.partner.lumen.point1": "• Entwicklung prädiktiver Modelle",
        "allies.partner.lumen.point2": "• Integration mehrerer Datenquellen",
        "allies.partner.andino.desc": "Kollektiv ehemaliger Diplomaten und B2G-Verhandler für Infrastrukturprojekte.",
        "allies.partner.andino.point1": "• Institutionelle Beziehungen",
        "allies.partner.andino.point2": "• Regulatorisches Management",
        "allies.partner.humboldt.desc": "Akademisches Spin-off, das DACH-Universitäten mit LATAM-Startups verbindet.",
        "allies.partner.humboldt.point1": "• Open-Innovation-Programme",
        "allies.partner.humboldt.point2": "• Technologietransfer",
        "allies.cta.kicker": "Erweiterte Zusammenarbeit",
        "allies.cta.title": "Ein lebendiges Netzwerk für Hochrisiko-/High-Impact-Projekte.",
        "allies.cta.desc": "Wir aktivieren Squads nach Bedarf: Data Scientists, Rechtsexperten, Wissenschaftsdiplomaten, strategische Storyteller.",
        "allies.cta.point1": "Teams in drei Zeitzonen koordiniert.",
        "allies.cta.point2": "Flexible Verträge: Pod, Retainer oder Sprint.",
        "allies.cta.point3": "Due diligence culturelle et technique avant chaque partenariat.",
        "allies.cta.join.title": "Möchten Sie Partner werden?",
        "allies.cta.join.desc": "Wir suchen Boutique-Firmen mit Ergebnisfokus. Wissenschaft, Technologie, Daten, Diplomatie, Expansion.",
        "allies.cta.join.btn.primary": "Partnerschaft anfragen",
        "allies.cta.join.btn.secondary": "Gespräch vereinbaren",
        
        // CONTACT
        "contact.sidebar.title": "Lassen Sie uns sprechen",
        "contact.sidebar.desc": "Wir sind bereit, Ihre Herausforderungen zu hören und zu zeigen, wie unser globales Netzwerk Ergebnisse beschleunigt.",
        "contact.sidebar.email.label": "E-Mail",
        "contact.sidebar.email.value": "contacto.gpmfsas@gmail.com",
        "contact.sidebar.location.label": "Standort",
        "contact.sidebar.location.city": "Bogotá, Kolumbien",
        "contact.sidebar.location.note": "Globale Operationen",
        "contact.form.title": "Senden Sie uns eine Nachricht",
        "contact.form.name": "Name",
        "contact.form.placeholder.name": "Ihr Name",
        "contact.form.company": "Unternehmen",
        "contact.form.placeholder.company": "Ihre Organisation",
        "contact.form.email": "Geschäftliche E-Mail",
        "contact.form.placeholder.email": "beispiel@firma.com",
        "contact.form.message": "Nachricht",
        "contact.form.placeholder.message": "Wie können wir helfen?",
        "contact.form.submit": "Nachricht senden",
        "nav.contact": "Buchen",

        // COOKIES
        "cookie.text": "Wir verwenden Cookies.",
        "cookie.btn": "Akzeptieren"
    },
    fr: {
        "nav.home": "Accueil",
        "nav.firm": "Cabinet",
        "nav.services": "Services",
        "nav.contact": "Réserver",
        "nav.int": "Internationalisation",
        "nav.data": "Données et IA",
        "nav.ai": "IA & Analytique",
        "nav.bizdev": "Expansion & Solutions Sectorielles",
        "nav.partners": "Alliés",
        "nav.team": "Équipe",

        "home.hero.title": "Naviguer dans la complexité grâce à",
        "home.hero.span": "l'intelligence stratégique.",
        "home.hero.desc": "Nous aidons les organisations à prospérer dans des écosystèmes complexes.",
        "home.hero.cta": "Parlons Stratégie",
        "home.hero.services": "Explorer les Services",
        "home.trust.title": "Confiance générée dans des écosystèmes mondiaux",

        "home.prop.title": "Notre Différence",
        "home.prop.1.title": "Connexion Mondiale",
        "home.prop.1.desc": "De véritables ponts entre l'Amérique latine et l'Europe.",
        "home.prop.2.title": "Approche Collaborative",
        "home.prop.2.desc": "Nous co-créons des solutions.",
        "home.prop.3.title": "Innovation Continue",
        "home.prop.3.desc": "La technologie au service de la stratégie.",

        "home.areas.title": "Domaines d'Expertise",
        "home.areas.desc": "Stratégie, gestion intelligente des données et formation interdisciplinaire.",
        "home.services.card1.title": "Internationalisation",
        "home.services.card1.desc": "Expansion à focale interculturelle. Du benchmarking au softlanding opérationnel.",
        "home.services.card1.bullet1": "Alliances stratégiques",
        "home.services.card1.bullet2": "Missions commerciales",
        "home.services.card2.title": "Gouvernance des Données",
        "home.services.card2.desc": "Nous transformons des données dispersées en actifs stratégiques pour des décisions éclairées.",
        "home.services.card2.bullet1": "Diagnostic de maturité",
        "home.services.card2.bullet2": "Architecture de données",
        "home.services.card3.title": "Gestion Interculturelle",
        "home.services.card3.desc": "Renforcement des capacités internes, du leadership et de la culture organisationnelle.",
        "home.services.card3.bullet1": "Formation des équipes",
        "home.services.card3.bullet2": "Planification stratégique",
        "home.services.card4.title": "Expansion & Solutions Sectorielles",
        "home.services.card4.desc": "Expansion, alliances et solutions sur mesure pour l’Agro-Tech, la science et la construction.",
        "home.services.card4.bullet1": "Diagnostic d’opportunité & feuille de route",
        "home.services.card4.bullet2": "Activation de partenariats & closing",
        "common.viewDetails": "Voir détails →",
        
        "home.why.title": "Pas de réponses toutes faites.",
        "home.why.span": "Nous co-créons des solutions.",
        "home.why.desc": "La valeur réside dans la capacité à transformer les données en action.",
        "home.why.pillar1.title": "Rigueur Méthodologique",
        "home.why.pillar1.desc": "Processus standardisés validés en Europe et en Amérique latine.",
        "home.why.pillar2.title": "Agilité Boutique",
        "home.why.pillar2.desc": "Attention directe des associés seniors, sans bureaucratie.",
        "home.why.pillar3.title": "Vision Globale",
        "home.why.pillar3.desc": "ADN trilingue et multiculturel natif.",
        "home.testimonial.quote": "GPMF a compris notre complexité technique et l'a traduite en une stratégie d'expansion claire et exécutable. Ils nous ont aidés à construire la capacité d'exécution.",
        "home.testimonial.person": "David A. Rachid",
        "home.testimonial.role": "CEO, DCR Exponential (USA)",
        "home.cta.title": "Prêt à élever le standard.",
        "home.cta.desc": "Planifiez une session de diagnostic stratégique de 30 minutes offerte.",
        "home.cta.btn.primary": "Demander un diagnostic",
        "home.cta.btn.secondary": "WhatsApp Direct",

        "about.hero.title": "Science et Stratégie.",
        "about.hero.subtitle": "Sans frontières.",
        "about.hero.desc": "GPMF est un hybride entre la rigueur de l'ingénierie et l'agilité des affaires mondiales.",
        "about.team.title": "Direction Senior",
        "about.team.desc": "Attention directe des associés.",
        "about.team.adriana.role": "Ingénierie & Complexité",
        "about.team.adriana.desc": "Ingénieure avec une large expérience en R&D, politiques publiques et systèmes complexes. Apporte structure et crédibilité technique.",
        "about.team.marcela.role": "Stratégie & Expansion",
        "about.team.marcela.desc": "Experte en développement des affaires et sourcing M&A, vision trilingue. Ouvre des marchés difficiles et négociations B2B/B2G.",
        "about.vision.title": "Notre Étoile Polaire",
        "about.vision.desc": "D'ici 2030, nous serons le cabinet de référence reliant l'Amérique latine, l'Europe et l'Amérique du Nord.",
        "about.vision.quote": "D'ici 2030, nous serons la boutique de référence reliant l'Amérique latine, l'Europe et l'Amérique du Nord, transformant la diversité culturelle et technologique en avantage compétitif.",
        "about.vision.stat1": "Continents",
        "about.vision.stat2": "Années d'expérience",
        "about.vision.stat3": "Attention senior",
        
        "allies.hero.kicker": "Réseau Global",
        "allies.hero.title": "Des personnes et des firmes qui amplifient notre impact",
        "allies.hero.desc": "Nous réunissons leadership senior, stratèges spécialisés et alliés institutionnels entre Europe, Amérique du Nord et Amérique latine pour débloquer des projets complexes.",
        "allies.core.kicker": "Core Team",
        "allies.core.title": "Associées et directeurs de pratique",
        "allies.core.subtitle": "Attention directe, sans intermédiaires juniors",
        "allies.core.marcela.role": "Network Management",
        "allies.core.marcela.desc": "Transformation digitale et expansion commerciale dans des écosystèmes trilingues ES/EN/DE.",
        "allies.core.adriana.role": "Innovation & Politiques Publiques",
        "allies.core.adriana.desc": "Ingénieure et stratégiste en science, agro et intelligence concurrentielle pour gouvernements et multilatéraux.",
        "allies.core.natalia.role": "Analyse & Opérations",
        "allies.core.natalia.desc": "Conception des opérations internes et analytique appliquée pour la scalabilité.",
        "allies.core.carlos.role": "Business Intelligence & IA",
        "allies.core.carlos.desc": "12+ ans en BI, stratégie data et déploiements IA entre LatAm et Europe.",
        "allies.partners.kicker": "Alliances",
        "allies.partners.title": "Partenaires et firmes associées",
        "allies.partners.subtitle": "Cellules spécialisées que nous mobilisons selon le projet",
        "allies.partner.atelier.desc": "Think tank sur la transition énergétique, la diplomatie climatique et le financement vert.",
        "allies.partner.atelier.point1": "• Conception de feuilles de route Net-Zero",
        "allies.partner.atelier.point2": "• Coordination avec les institutions de l'UE",
        "allies.partner.nordic.desc": "Studio boutique pour softlanding juridique et commercial des scaleups tech.",
        "allies.partner.nordic.point1": "• Structuration juridique dans l'UE",
        "allies.partner.nordic.point2": "• Accès à des fonds et hubs digitaux",
        "allies.partner.agro.desc": "Réseau d'experts en bioéconomie, agrotech et transfert technologique.",
        "allies.partner.agro.point1": "• Projets de coopération internationale",
        "allies.partner.agro.point2": "• Intelligence concurrentielle sectorielle",
        "allies.partner.lumen.desc": "Laboratoire d'IA appliquée pour le retail, la santé et l'industrie avancée.",
        "allies.partner.lumen.point1": "• Développement de modèles prédictifs",
        "allies.partner.lumen.point2": "• Intégration de données multi-sources",
        "allies.partner.andino.desc": "Collectif d'anciens diplomates et négociateurs B2G pour les projets d'infrastructure.",
        "allies.partner.andino.point1": "• Relations institutionnelles",
        "allies.partner.andino.point2": "• Gestion réglementaire",
        "allies.partner.humboldt.desc": "Spin-off académique reliant les universités DACH aux startups latino-américaines.",
        "allies.partner.humboldt.point1": "• Programmes d'innovation ouverte",
        "allies.partner.humboldt.point2": "• Transfert technologique",
        "allies.cta.kicker": "Collaboration étendue",
        "allies.cta.title": "Un réseau vivant pour des projets à haut risque et haut impact.",
        "allies.cta.desc": "Nous activons des squads selon le défi : data scientists, juristes, diplomates scientifiques, storytellers stratégiques.",
        "allies.cta.point1": "Équipes transnationales coordonnées sur trois fuseaux horaires.",
        "allies.cta.point2": "Contrats flexibles : pod, retainer ou accélération par sprint.",
        "allies.cta.point3": "Due diligence culturelle et technique avant chaque partenariat.",
        "allies.cta.join.title": "Envie de rejoindre l'alliance ?",
        "allies.cta.join.desc": "Nous recherchons des firmes boutique orientées résultats. Science, technologie, data, diplomatie, expansion.",
        "allies.cta.join.btn.primary": "Proposer une alliance",
        "allies.cta.join.btn.secondary": "Planifier un échange",
        
        // CONTACT
        "contact.sidebar.title": "Discutons",
        "contact.sidebar.desc": "Nous sommes prêts à écouter vos défis et à activer notre réseau mondial pour accélérer vos résultats.",
        "contact.sidebar.email.label": "Email",
        "contact.sidebar.email.value": "contacto.gpmfsas@gmail.com",
        "contact.sidebar.location.label": "Localisation",
        "contact.sidebar.location.city": "Bogotá, Colombie",
        "contact.sidebar.location.note": "Opérations globales",
        "contact.form.title": "Envoyez-nous un message",
        "contact.form.name": "Nom",
        "contact.form.placeholder.name": "Votre nom",
        "contact.form.company": "Entreprise",
        "contact.form.placeholder.company": "Votre organisation",
        "contact.form.email": "Email professionnel",
        "contact.form.placeholder.email": "exemple@entreprise.com",
        "contact.form.message": "Message",
        "contact.form.placeholder.message": "Comment pouvons-nous vous aider ?",
        "contact.form.submit": "Envoyer",

        "cookie.text": "Nous utilisons des cookies.",
        "cookie.btn": "Accepter"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('gpmf-lang', lang);
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            if(element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[lang][key];
            } else {
                element.textContent = translations[lang][key];
            }
        }
    });
    document.querySelectorAll('.lang-btn').forEach(btn => {
        if(btn.dataset.lang === lang) {
            btn.classList.add('text-burgundy', 'font-bold');
            btn.classList.remove('text-gray-400');
        } else {
            btn.classList.remove('text-burgundy', 'font-bold');
            btn.classList.add('text-gray-400');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('gpmf-lang') || 'es';
    changeLanguage(savedLang);
    
    const menuBtn = document.getElementById('mobile-menu-btn');
    const mobileMenu = document.getElementById('mobile-menu');
    if(menuBtn && mobileMenu) {
        menuBtn.addEventListener('click', () => {
            mobileMenu.classList.toggle('hidden');
            mobileMenu.classList.toggle('flex');
        });
    }

    document.querySelectorAll('.mobile-services-toggle').forEach(button => {
        const panel = button.nextElementSibling;
        button.addEventListener('click', () => {
            const expanded = button.getAttribute('aria-expanded') === 'true';
            button.setAttribute('aria-expanded', (!expanded).toString());
            if(panel) {
                panel.classList.toggle('hidden');
            }
            const icon = button.querySelector('svg');
            if(icon) {
                icon.classList.toggle('rotate-180');
            }
        });
    });
});

function acceptCookies() {
    localStorage.setItem('gpmf-cookie-consent', 'true');
    document.getElementById('cookie-banner').classList.add('hidden');
}