/* GPMF MAIN CONTROLLER - V3.0 (FINAL) */

const translations = {
    es: {
        // MENÚ
        "nav.home": "Inicio",
        "nav.firm": "Firma",
        "nav.services": "Servicios",
        "nav.contact": "Agendar",
        "nav.int": "Internacionalización",
        "nav.data": "Datos e IA",
        "nav.ai": "IA & Analítica",
        "nav.bizdev": "Expansión & Soluciones Sectoriales",
        "nav.partners": "Aliados",
        "nav.team": "Equipo",

        // HOME - HERO
        "home.hero.title": "Navegando la complejidad global a través de",
        "home.hero.span": "inteligencia estratégica.",
        "home.hero.desc": "Ayudamos a organizaciones a prosperar en ecosistemas complejos mediante gestión multidisciplinaria, intercultural y transformación basada en datos.",
        "home.hero.cta": "Planes estratégicos", // ← New change
        "home.hero.services": "Hablemos de su estrategia",
        "home.trust.title": "Confianza generada en ecosistemas globales",

        // HOME - PROPUESTA VALOR (ICONOS)
        "home.prop.title": "Nuestra Diferencia",
        "home.prop.1.title": "Conexión Global",
        "home.prop.1.desc": "Puentes reales entre ecosistemas de LatAm y Europa.",
        "home.prop.2.title": "Enfoque Colaborativo",
        "home.prop.2.desc": "Co-creamos soluciones, no imponemos respuestas.",
        "home.prop.3.title": "Innovación Continua",
        "home.prop.3.desc": "Tecnología y datos al servicio de la estrategia humana.",

        // HOME - AREAS
        "home.areas.title": "Áreas de Práctica",
        "home.areas.desc": "Unimos estrategia, gestión inteligente de datos y formación interdisciplinaria.",
        "home.services.card1.title": "Internacionalización",
        "home.services.card1.desc": "Expansión con enfoque intercultural. Desde benchmarking hasta softlanding operativo.",
        "home.services.card1.bullet1": "Alianzas Estratégicas",
        "home.services.card1.bullet2": "Misiones Comerciales",
        "home.services.card2.title": "Gobernanza de Datos",
        "home.services.card2.desc": "Convertimos datos dispersos en activos estratégicos para decisiones informadas.",
        "home.services.card2.bullet1": "Diagnóstico de Madurez",
        "home.services.card2.bullet2": "Arquitectura de Datos",
        "home.services.card3.title": "Gestión Intercultural",
        "home.services.card3.desc": "Fortalecimiento de capacidades internas, liderazgo y cultura organizacional.",
        "home.services.card3.bullet1": "Entrenamiento Equipos",
        "home.services.card3.bullet2": "Planeación Estratégica",
        "home.services.card4.title": "Expansión & Soluciones Sectoriales",
        "home.services.card4.desc": "Expansión, alianzas y soluciones a medida para Agro-Tech, Ciencia y Construcción.",
        "home.services.card4.bullet1": "Diagnóstico + roadmap internacional",
        "home.services.card4.bullet2": "Red global y cierre de alianzas",
        "common.viewDetails": "Ver detalles →",

        // HOME - WHY
        "home.why.title": "No traemos respuestas enlatadas.",
        "home.why.span": "Co-creamos soluciones.",
        "home.why.desc": "En un mundo saturado de información, el valor no está en los datos, sino en la capacidad de transformarlos en acción.",
        "home.why.pillar1.title": "Rigurosidad Metodológica",
        "home.why.pillar1.desc": "Procesos estandarizados validados en Europa y Latam.",
        "home.why.pillar2.title": "Agilidad Boutique",
        "home.why.pillar2.desc": "Atención directa de socias senior, sin burocracia.",
        "home.why.pillar3.title": "Visión Global",
        "home.why.pillar3.desc": "ADN trilingüe y multicultural nativo.",
        "home.testimonial.quote": "GPMF entendió nuestra complejidad técnica y la tradujo en una estrategia de expansión clara y ejecutable. No solo nos dieron un plan, nos ayudaron a construir la capacidad para ejecutarlo.",
        "home.testimonial.person": "Natalia Sánchez",
        "home.testimonial.role": "CEO, DCR Exponential (USA)",
        "home.cta.title": "Listo para elevar el estándar.",
        "home.cta.desc": "Agende una sesión de diagnóstico estratégico de 30 minutos sin costo.",
        "home.cta.btn.primary": "Solicitar Diagnóstico",
        "home.cta.btn.secondary": "Solicitar Diagnóstico",

        // ABOUT
        "about.hero.title": "Ciencia y Estrategia.",
        "about.hero.subtitle": "Sin fronteras.",
        "about.hero.desc": "GPMF no es una consultora tradicional. Somos un híbrido entre la rigurosidad de la ingeniería y la agilidad de los negocios globales.",
        "about.team.title": "Liderazgo Senior",
        "about.team.desc": "Atención directa de las socias. Sin intermediarios junior.",
        "about.team.adriana.role": "Ingeniería & Complejidad",
        "about.team.adriana.desc": "Ingeniera con amplia trayectoria en R&D, políticas públicas y sistemas complejos (INRAE, Colciencias). Aporta estructura sistémica y credibilidad técnica.",
        "about.team.marcela.role": "Estrategia & Expansión",
        "about.team.marcela.desc": "Experta en desarrollo de negocios y M&A Sourcing con visión trilingüe (ES/EN/DE). Abre mercados complejos y negociaciones B2B/B2G de alto ticket.",
        "about.vision.title": "Nuestra Estrella Norte",
        "about.vision.desc": "Para 2030, seremos la firma boutique de referencia que conecta Latinoamérica, Europa y Norteamérica.",
        "about.vision.quote": "Para 2030, seremos la firma boutique de referencia que conecta Latinoamérica, Europa y Norteamérica, transformando la diversidad cultural y tecnológica en ventaja competitiva.",
        "about.vision.stat1": "Continentes",
        "about.vision.stat2": "Años Exp. Conjunta",
        "about.vision.stat3": "Atención Senior",

        // ALLIES PAGE
        "allies.hero.kicker": "Red Global",
        "allies.hero.title": "Personas y Firmas que amplifican nuestro impacto",
        "allies.hero.desc": "Unimos liderazgo senior, estrategas especializados y aliados institucionales en Europa, Norteamérica y Latinoamérica para desbloquear proyectos complejos.",
        "allies.core.kicker": "Core Team",
        "allies.core.title": "Socias y directores de práctica",
        "allies.core.subtitle": "Atención directa, sin intermediarios junior",
        "allies.core.marcela.role": "Network Management",
        "allies.core.marcela.desc": "Transformación digital y expansión comercial en ecosistemas trinlingües ES/EN/DE.",
        "allies.core.adriana.role": "Innovation & Políticas Públicas",
        "allies.core.adriana.desc": "Ingeniera y estratega en ciencia, agro e inteligencia competitiva para gobiernos y multilaterales.",
        "allies.core.natalia.role": "Análisis & Operaciones",
        "allies.core.natalia.desc": "Diseño de operaciones internas y analítica aplicada para escalabilidad organizacional.",
        "allies.core.carlos.role": "Business Intelligence & IA",
        "allies.core.carlos.desc": "12+ años en BI, data strategy y despliegues de IA para corporaciones LatAm-Europa.",
        "allies.partners.kicker": "Alianzas",
        "allies.partners.title": "Partners y firmas asociadas",
        "allies.partners.subtitle": "Células especializadas que extendemos según el proyecto",
        "allies.partner.atelier.desc": "Think tank en transición energética, diplomacia climática y financiamiento verde.",
        "allies.partner.atelier.point1": "• Diseño de hojas de ruta Net-Zero",
        "allies.partner.atelier.point2": "• Coordinación con instituciones UE",
        "allies.partner.nordic.desc": "Estudio boutique en softlanding legal y comercial para scaleups tecnológicas.",
        "allies.partner.nordic.point1": "• Estructuración societaria UE",
        "allies.partner.nordic.point2": "• Acceso a fondos y hubs digitales",
        "allies.partner.agro.desc": "Red de expertos en bioeconomía, agrotech y transferencia tecnológica.",
        "allies.partner.agro.point1": "• Proyectos de cooperación internacional",
        "allies.partner.agro.point2": "• Inteligencia competitiva sectorial",
        "allies.partner.lumen.desc": "Laboratorio de IA aplicada en retail, salud y manufactura avanzada.",
        "allies.partner.lumen.point1": "• Desarrollo de modelos predictivos",
        "allies.partner.lumen.point2": "• Integración de datos multi-fuente",
        "allies.partner.andino.desc": "Colectivo de ex diplomáticos y negociadores B2G para proyectos de infraestructura.",
        "allies.partner.andino.point1": "• Relacionamiento institucional",
        "allies.partner.andino.point2": "• Gestión regulatoria",
        "allies.partner.humboldt.desc": "Spin-off académico que conecta universidades DACH con startups latinoamericanas.",
        "allies.partner.humboldt.point1": "• Programas de innovación abierta",
        "allies.partner.humboldt.point2": "• Transferencia tecnológica",
        "allies.cta.kicker": "Colaboración Extendida",
        "allies.cta.title": "Una red viva para proyectos de alto riesgo y alto impacto.",
        "allies.cta.desc": "Activamos squads según el reto: data scientists, expertos legales, diplomáticos científicos, storytellers estratégicos. Todo integrado bajo el mismo playbook.",
        "allies.cta.point1": "Equipos transnacionales coordinados en tres zonas horarias.",
        "allies.cta.point2": "Contratos flexibles: pod, retainer o aceleración por sprint.",
        "allies.cta.point3": "Due diligence cultural y técnica antes de cada partnership.",
        "allies.cta.join.title": "¿Quieres sumarte como aliado?",
        "allies.cta.join.desc": "Buscamos firmas y profesionales con ADN boutique y enfoque en resultados. Ciencia, tecnología, data, diplomacia y expansión.",
        "allies.cta.join.btn.primary": "Postular alianza",
        "allies.cta.join.btn.secondary": "Agendar conversación",

        // CONTACT
        "contact.sidebar.title": "Conversemos",
        "contact.sidebar.desc": "Estamos listos para escuchar sus desafíos y explorar cómo nuestra red global puede acelerar sus resultados.",
        "contact.sidebar.email.label": "Email",
        "contact.sidebar.email.value": "contacto.gpmfsas@gmail.com",
        "contact.sidebar.location.label": "Ubicación",
        "contact.sidebar.location.city": "Bogotá, Colombia",
        "contact.sidebar.location.note": "Operaciones Globales",
        "contact.form.title": "Envíenos un mensaje",
        "contact.form.name": "Nombre",
        "contact.form.placeholder.name": "Su nombre",
        "contact.form.company": "Empresa",
        "contact.form.placeholder.company": "Su organización",
        "contact.form.email": "Email Corporativo",
        "contact.form.placeholder.email": "ejemplo@empresa.com",
        "contact.form.message": "Mensaje",
        "contact.form.placeholder.message": "¿Cómo podemos ayudarle?",
        "contact.form.submit": "Enviar Mensaje",
        "nav.contact": "Agendar",

        // COOKIES
        "cookie.text": "Utilizamos cookies para mejorar su experiencia.",
        "cookie.btn": "Aceptar",

        // SERVICIOS - INTERNACIONALIZACIÓN
        "int.hero.title1": "Expanda su Negocio Globalmente:",
        "int.hero.title2": "Internacionalización Estratégica",
        "int.hero.title3": "y Alianzas con Propósito",
        "int.hero.desc": "En GPMF, somos su socio estratégico para navegar mercados internacionales, construir alianzas sólidas y asegurar una entrada exitosa (soft landing) en Europa y América Latina, transformando desafíos culturales en ventajas competitivas duraderas.",
        "int.hero.cta": "Solicite su Diagnóstico Estratégico Gratuito",
        "int.method.title": "Metodología Probada y Orientada a Resultados",
        "int.method.desc": "En GPMF, vamos más allá de la teoría. Le ayudamos a generar valor real y medible, convirtiendo la analítica y la IA en el núcleo de su estrategia y eficiencia operativa.",
        "int.method.step1.title": "Análisis Riguroso",
        "int.method.step1.desc": "Nuestra metodología combina análisis riguroso, inteligencia contextual y facilitación de alianzas clave para construir propuestas sólidas y sostenibles.",
        "int.method.step2.title": "Backward Planning",
        "int.method.step2.desc": "Planificación hacia atrás para definir objetivos claros a largo plazo y trazar los pasos tecnológicos y organizacionales.",
        "int.method.step3.title": "Forward Planning",
        "int.method.step3.desc": "Diseñamos una estrategia de salida al mercado con pilotajes en ciclos cortos para aprender, ajustar y escalar rápidamente, generando \"victorias rápidas\" y hoja de ruta de expansión.",
        "int.focus.title": "Nuestro Enfoque Distintivo",
        "int.focus.1.bold": "Global e Interdisciplinario:",
        "int.focus.1.text": "Combinamos expertise internacional con conocimiento sectorial profundo",
        "int.focus.2.bold": "Enfoque Intercultural:",
        "int.focus.2.text": "Transformamos barreras culturales en ventajas competitivas",
        "int.focus.3.bold": "Impulso por Datos:",
        "int.focus.3.text": "Decisiones basadas en analítica avanzada e inteligencia artificial",
        "int.focus.4.bold": "Resultados Medibles:",
        "int.focus.4.text": "Cada iniciativa tiene KPIs claros y seguimiento continuo",
        "int.services.title": "Nuestros Servicios Clave",
        "int.services.subtitle": "Soluciones integrales para su internacionalización y desarrollo de alianzas estratégicas",
        "int.services.card1.title": "Desarrollo de Negocios y Alianzas Estratégicas",
        "int.services.card1.desc": "Ayuda a identificar oportunidades de crecimiento y establecer alianzas estratégicas en mercados globales.",
        "int.services.card1.b1": "• Diagnóstico de capacidades",
        "int.services.card1.b2": "• Mapeo de actores estratégicos",
        "int.services.card1.b3": "• Diseño de propuestas colaborativas",
        "int.services.card1.b4": "• Facilitación de negociaciones",
        "int.services.card2.title": "Diseño Estratégico para Matching Funds",
        "int.services.card2.desc": "Apoyo para ampliar impacto y financiamiento mediante acceso a fondos de cofinanciación.",
        "int.services.card2.b1": "• Identificación de oportunidades",
        "int.services.card2.b2": "• Formulación de propuestas alineadas",
        "int.services.card2.b3": "• Integración de alianzas estratégicas",
        "int.services.card2.b4": "• Gestión de fondos europeos",
        "int.services.card3.title": "Desarrollo de Habilidades Interculturales",
        "int.services.card3.desc": "Programas de formación para fortalecer competencias en equipos multiculturales.",
        "int.services.card3.b1": "• Comunicación intercultural",
        "int.services.card3.b2": "• Gestión de equipos diversos",
        "int.services.card3.b3": "• Negociación intercultural",
        "int.services.card3.b4": "• Adaptación organizacional",
        "int.services.card4.title": "Coordinación de Equipos Multiculturales",
        "int.services.card4.desc": "Gestión y acompañamiento para facilitar comunicación y colaboración global.",
        "int.services.card4.b1": "• Facilitación de reuniones",
        "int.services.card4.b2": "• Resolución de conflictos",
        "int.services.card4.b3": "• Creación de ambientes inclusivos",
        "int.services.card4.b4": "• Coaching intercultural",
        "int.services.card5.title": "Benchmarking Internacional",
        "int.services.card5.desc": "Análisis comparativo de mejores prácticas globales para adaptación local.",
        "int.services.card5.b1": "• Análisis de competidores",
        "int.services.card5.b2": "• Estudios de mejores prácticas",
        "int.services.card5.b3": "• Adaptación de modelos",
        "int.services.card5.b4": "• Informes estratégicos",
        "int.services.card6.title": "Solución Integral",
        "int.services.card6.desc": "Combine múltiples servicios para una transformación completa de su expansión internacional.",
        "int.services.card6.cta": "Consultar Paquete Completo",
        "int.cases.title": "Casos de Éxito con GPMF",
        "int.cases.subtitle": "Descubra cómo hemos transformado problemas en oportunidades para nuestros clientes",
        "int.cases.1.title": "Casa Normandía",
        "int.cases.1.subtitle": "Estrategia de Salida al Mercado Internacional",
        "int.cases.1.desc": "Diseñamos una estrategia de salida al mercado con pilotajes en ciclos cortos para aprender, ajustar y escalar rápidamente, generando \"victorias rápidas\" y hoja de ruta de expansión.",
        "int.cases.1.b1": "Estrategia de internacionalización completa",
        "int.cases.1.b2": "Pilotajes en ciclos cortos y ajustes rápidos",
        "int.cases.1.b3": "Hoja de ruta de expansión clara",
        "int.cases.2.title": "Instituto Científico Alemán-Colombiano",
        "int.cases.2.subtitle": "Desarrollo de Alianzas Estratégicas",
        "int.cases.2.desc": "Se apoyó a un instituto científico alemán-colombiano a diseñar y ejecutar una estrategia de alianzas que generó un crecimiento sostenido de más del 10% anual.",
        "int.cases.2.b1": "Gestión de fondos por más de €500.000",
        "int.cases.2.b2": "Crecimiento anual superior al 10%",
        "int.cases.2.b3": "Red de 15+ aliados estratégicos",
        "int.relations.title": "Relaciones Internacionales e Interculturales",
        "int.relations.subtitle": "Construimos puentes entre culturas y mercados, transformando la diversidad en ventaja competitiva",
        "int.relations.c1.title": "Conexiones Globales",
        "int.relations.c1.desc": "Facilitamos alianzas estratégicas entre empresas de diferentes continentes y culturas.",
        "int.relations.c2.title": "Equipos Diversos",
        "int.relations.c2.desc": "Desarrollamos competencias interculturales para equipos multiculturales de alto rendimiento.",
        "int.relations.c3.title": "Expansión Sostenible",
        "int.relations.c3.desc": "Diseñamos estrategias de entrada a mercados que aseguren crecimiento sostenible a largo plazo.",
        "int.pain.title": "¿Su Empresa Enfrenta Estos Desafíos?",
        "int.pain.subtitle": "Comprendemos sus \"puntos de dolor\" y hemos diseñado soluciones específicas para cada obstáculo",
        "int.pain.c1.title": "Expansión sin Estrategia",
        "int.pain.c1.desc": "¿Su empresa busca expandirse internacionalmente pero le faltan los contactos o la estrategia clara?",
        "int.pain.c2.title": "Barreras Culturales",
        "int.pain.c2.desc": "¿Necesita establecer alianzas estratégicas pero enfrenta barreras culturales o normativas?",
        "int.pain.c3.title": "Soft Landing Riesgoso",
        "int.pain.c3.desc": "¿Le preocupa una entrada a nuevos mercados sin preparación cultural y logística adecuada?",
        "int.pain.c4.title": "Financiación Ineficiente",
        "int.pain.c4.desc": "¿Sus iniciativas de financiación internacional carecen de diseño estratégico para acceder a fondos de cofinanciación?",
        "int.pain.c5.title": "Competencias Interculturales",
        "int.pain.c5.desc": "¿Su equipo necesita fortalecer sus competencias interculturales para operar eficazmente globalmente?",
        "int.pain.c6.title": "Análisis Insuficiente",
        "int.pain.c6.desc": "¿Toma decisiones de expansión basadas en intuición en lugar de datos y análisis contextual?",
        "int.cta.title": "Dé el Primer Paso",
        "int.cta.desc": "No espere a que la competencia le gane la delantera. Nuestro diagnóstico inicial es la forma más rápida de obtener un plan de acción claro y comenzar a transformar su negocio globalmente.",
        "int.cta.btn": "¡Quiero mi Diagnóstico Estratégico Gratuito!",
        "int.cta.list_title": "Complete el formulario y recibirá:",
        "int.cta.list.1": "Análisis gratuito de su potencial de internacionalización",
        "int.cta.list.2": "Recomendaciones personalizadas en 48 horas",
        "int.cta.list.3": "Hoja de ruta inicial para su expansión global",
    },
    en: {
        "nav.home": "Home",
        "nav.firm": "Firm",
        "nav.services": "Services",
        "nav.contact": "Book Now",
        "nav.int": "Internationalization",
        "nav.data": "Data & AI",
        "nav.ai": "AI & Analytics",
        "nav.bizdev": "Expansion & Sector Solutions",
        "nav.partners": "Allies",
        "nav.team": "Team",

        "home.hero.title": "Navigating global complexity through",
        "home.hero.span": "strategic intelligence.",
        "home.hero.desc": "We help organizations thrive in complex ecosystems through multidisciplinary management, intercultural expertise, and data-driven transformation.",
        "home.hero.cta": "Let's Discuss Strategy",
        "home.hero.services": "Explore Services",
        "home.trust.title": "Trusted across global ecosystems",

        "home.prop.title": "Our Difference",
        "home.prop.1.title": "Global Connection",
        "home.prop.1.desc": "Real bridges between LatAm and European ecosystems.",
        "home.prop.2.title": "Collaborative Approach",
        "home.prop.2.desc": "We co-create solutions, we don't impose answers.",
        "home.prop.3.title": "Continuous Innovation",
        "home.prop.3.desc": "Technology and data at the service of human strategy.",

        "home.areas.title": "Practice Areas",
        "home.areas.desc": "We unite strategy, intelligent data management, and interdisciplinary training.",
        "home.services.card1.title": "Internationalization",
        "home.services.card1.desc": "Expansion with an intercultural focus. From benchmarking to operational softlanding.",
        "home.services.card1.bullet1": "Strategic Alliances",
        "home.services.card1.bullet2": "Trade Missions",
        "home.services.card2.title": "Data Governance",
        "home.services.card2.desc": "We turn scattered data into strategic assets for informed decisions.",
        "home.services.card2.bullet1": "Maturity Assessment",
        "home.services.card2.bullet2": "Data Architecture",
        "home.services.card3.title": "Intercultural Management",
        "home.services.card3.desc": "Strengthening internal capabilities, leadership, and organizational culture.",
        "home.services.card3.bullet1": "Team Training",
        "home.services.card3.bullet2": "Strategic Planning",
        "home.services.card4.title": "Expansion & Sector Solutions",
        "home.services.card4.desc": "Expansion, alliances, and tailored plays for Agro-Tech, Science, and Construction.",
        "home.services.card4.bullet1": "Opportunity diagnostic & global roadmap",
        "home.services.card4.bullet2": "Partnership activation & deal support",
        "common.viewDetails": "View details →",

        "home.why.title": "No canned answers.",
        "home.why.span": "We co-create solutions.",
        "home.why.desc": "In an information-saturated world, value lies not in data, but in the ability to transform it into action.",
        "home.why.pillar1.title": "Methodological Rigor",
        "home.why.pillar1.desc": "Standardized processes validated in Europe and LatAm.",
        "home.why.pillar2.title": "Boutique Agility",
        "home.why.pillar2.desc": "Direct senior partner attention, zero bureaucracy.",
        "home.why.pillar3.title": "Global Vision",
        "home.why.pillar3.desc": "Native trilingual and multicultural DNA.",
        "home.testimonial.quote": "GPMF understood our technical complexity and turned it into a clear, executable expansion strategy. They didn’t just deliver a plan—they helped us build the capacity to execute it.",
        "home.testimonial.person": "David A. Rachid",
        "home.testimonial.role": "CEO, DCR Exponential (USA)",
        "home.cta.title": "Ready to raise the standard.",
        "home.cta.desc": "Book a complimentary 30-minute strategic diagnostic session.",
        "home.cta.btn.primary": "Request Diagnostic",
        "home.cta.btn.secondary": "Solicitar Diagnóstico",

        "about.hero.title": "Science and Strategy.",
        "about.hero.subtitle": "Borderless.",
        "about.hero.desc": "GPMF is not a traditional consulting firm. We are a hybrid between engineering rigor and global business agility.",
        "about.team.title": "Senior Leadership",
        "about.team.desc": "Direct attention from partners. No junior intermediaries.",
        "about.team.adriana.role": "Engineering & Complexity",
        "about.team.adriana.desc": "Engineer with extensive experience in R&D, public policy, and complex systems (INRAE, Colciencias). Brings systemic structure and technical credibility.",
        "about.team.marcela.role": "Strategy & Expansion",
        "about.team.marcela.desc": "Expert in Business Development and M&A sourcing with trilingual vision (ES/EN/DE). Opens difficult markets and high-ticket B2B/B2G negotiations.",
        "about.vision.title": "Our North Star",
        "about.vision.desc": "By 2030, we will be the boutique firm of reference connecting Latin America, Europe, and North America.",
        "about.vision.quote": "By 2030, we will be the boutique firm of reference connecting Latin America, Europe, and North America, turning cultural and technological diversity into a competitive edge.",
        "about.vision.stat1": "Continents",
        "about.vision.stat2": "Years Combined Experience",
        "about.vision.stat3": "Senior Attention",

        "allies.hero.kicker": "Global Network",
        "allies.hero.title": "People and Firms that amplify our impact",
        "allies.hero.desc": "We bring together senior leadership, specialized strategists, and institutional allies across Europe, North America, and Latin America to unlock complex projects.",
        "allies.core.kicker": "Core Team",
        "allies.core.title": "Partners and practice directors",
        "allies.core.subtitle": "Direct attention, no junior intermediaries",
        "allies.core.marcela.role": "Network Management",
        "allies.core.marcela.desc": "Digital transformation and business expansion across trilingual ES/EN/DE ecosystems.",
        "allies.core.adriana.role": "Innovation & Public Policy",
        "allies.core.adriana.desc": "Engineer and strategist in science, agro, and competitive intelligence for governments and multilaterals.",
        "allies.core.natalia.role": "Analytics & Operations",
        "allies.core.natalia.desc": "Design of internal operations and applied analytics for organizational scalability.",
        "allies.core.carlos.role": "Business Intelligence & AI",
        "allies.core.carlos.desc": "12+ years in BI, data strategy, and AI deployments for LatAm–Europe corporations.",
        "allies.partners.kicker": "Alliances",
        "allies.partners.title": "Partner firms and associates",
        "allies.partners.subtitle": "Specialized cells we deploy per project",
        "allies.partner.atelier.desc": "Think tank in energy transition, climate diplomacy, and green finance.",
        "allies.partner.atelier.point1": "• Net-zero roadmap design",
        "allies.partner.atelier.point2": "• Coordination with EU institutions",
        "allies.partner.nordic.desc": "Boutique studio for legal and commercial softlanding of tech scaleups.",
        "allies.partner.nordic.point1": "• EU corporate structuring",
        "allies.partner.nordic.point2": "• Access to funds and digital hubs",
        "allies.partner.agro.desc": "Network of experts in bioeconomy, agrotech, and technology transfer.",
        "allies.partner.agro.point1": "• International cooperation projects",
        "allies.partner.agro.point2": "• Sector competitive intelligence",
        "allies.partner.lumen.desc": "AI applied lab for retail, health, and advanced manufacturing.",
        "allies.partner.lumen.point1": "• Predictive model development",
        "allies.partner.lumen.point2": "• Multi-source data integration",
        "allies.partner.andino.desc": "Collective of former diplomats and B2G negotiators for infrastructure projects.",
        "allies.partner.andino.point1": "• Institutional relationship management",
        "allies.partner.andino.point2": "• Regulatory management",
        "allies.partner.humboldt.desc": "Academic spin-off connecting DACH universities with Latin American startups.",
        "allies.partner.humboldt.point1": "• Open innovation programs",
        "allies.partner.humboldt.point2": "• Technology transfer",
        "allies.cta.kicker": "Extended Collaboration",
        "allies.cta.title": "A living network for high-risk, high-impact projects.",
        "allies.cta.desc": "We activate squads per challenge: data scientists, legal experts, science diplomats, strategic storytellers.",
        "allies.cta.point1": "Transnational teams coordinated across three time zones.",
        "allies.cta.point2": "Flexible contracts: pod, retainer, or sprint acceleration.",
        "allies.cta.point3": "Cultural and technical due diligence before every partnership.",
        "allies.cta.join.title": "Want to join as an ally?",
        "allies.cta.join.desc": "We look for boutique DNA firms focused on outcomes. Science, technology, data, diplomacy, and expansion.",
        "allies.cta.join.btn.primary": "Apply partnership",
        "allies.cta.join.btn.secondary": "Book a conversation",

        // CONTACT
        "contact.sidebar.title": "Let's connect",
        "contact.sidebar.desc": "We're ready to listen to your challenges and explore how our global network can accelerate your results.",
        "contact.sidebar.email.label": "Email",
        "contact.sidebar.email.value": "contacto.gpmfsas@gmail.com",
        "contact.sidebar.location.label": "Location",
        "contact.sidebar.location.city": "Bogotá, Colombia",
        "contact.sidebar.location.note": "Global operations",
        "contact.form.title": "Send us a message",
        "contact.form.name": "Name",
        "contact.form.placeholder.name": "Your name",
        "contact.form.company": "Company",
        "contact.form.placeholder.company": "Your organization",
        "contact.form.email": "Corporate Email",
        "contact.form.placeholder.email": "example@company.com",
        "contact.form.message": "Message",
        "contact.form.placeholder.message": "How can we help?",
        "contact.form.submit": "Send Message",
        "nav.contact": "Book Now",
        "cookie.text": "We use cookies to improve your experience.",
        "cookie.btn": "Accept",

        // SERVICES - INTERNATIONALIZATION
        "int.hero.title1": "Expand Your Business Globally:",
        "int.hero.title2": "Strategic Internationalization",
        "int.hero.title3": "and Purpose-Driven Alliances",
        "int.hero.desc": "At GPMF, we are your strategic partner to navigate international markets, build solid alliances, and ensure a successful soft landing in Europe and Latin America, transforming cultural challenges into lasting competitive advantages.",
        "int.hero.cta": "Request Your Free Strategic Diagnostic",
        "int.method.title": "Proven and Results-Oriented Methodology",
        "int.method.desc": "At GPMF, we go beyond theory. We help you generate real and measurable value, turning analytics and AI into the core of your strategy and operational efficiency.",
        "int.method.step1.title": "Rigorous Analysis",
        "int.method.step1.desc": "Our methodology combines rigorous analysis, contextual intelligence, and facilitation of key alliances to build solid and sustainable proposals.",
        "int.method.step2.title": "Backward Planning",
        "int.method.step2.desc": "Backward planning to define clear long-term objectives and map out technological and organizational steps.",
        "int.method.step3.title": "Forward Planning",
        "int.method.step3.desc": "We design a market entry strategy with short-cycle pilots to learn, adjust, and scale quickly, generating 'quick wins' and an expansion roadmap.",
        "int.focus.title": "Our Distinctive Focus",
        "int.focus.1.bold": "Global and Interdisciplinary:",
        "int.focus.1.text": "We combine international expertise with deep sector knowledge",
        "int.focus.2.bold": "Intercultural Focus:",
        "int.focus.2.text": "We transform cultural barriers into competitive advantages",
        "int.focus.3.bold": "Data-Driven:",
        "int.focus.3.text": "Decisions based on advanced analytics and artificial intelligence",
        "int.focus.4.bold": "Measurable Results:",
        "int.focus.4.text": "Every initiative has clear KPIs and continuous monitoring",
        "int.services.title": "Our Key Services",
        "int.services.subtitle": "Comprehensive solutions for your internationalization and strategic alliance development",
        "int.services.card1.title": "Business Development and Strategic Alliances",
        "int.services.card1.desc": "Helps identify growth opportunities and establish strategic alliances in global markets.",
        "int.services.card1.b1": "• Capability diagnostic",
        "int.services.card1.b2": "• Strategic stakeholder mapping",
        "int.services.card1.b3": "• Collaborative proposal design",
        "int.services.card1.b4": "• Negotiation facilitation",
        "int.services.card2.title": "Strategic Design for Matching Funds",
        "int.services.card2.desc": "Support to expand impact and funding through access to co-financing funds.",
        "int.services.card2.b1": "• Opportunity identification",
        "int.services.card2.b2": "• Aligned proposal formulation",
        "int.services.card2.b3": "• Strategic alliance integration",
        "int.services.card2.b4": "• European fund management",
        "int.services.card3.title": "Intercultural Skills Development",
        "int.services.card3.desc": "Training programs to strengthen competencies in multicultural teams.",
        "int.services.card3.b1": "• Intercultural communication",
        "int.services.card3.b2": "• Diverse team management",
        "int.services.card3.b3": "• Intercultural negotiation",
        "int.services.card3.b4": "• Organizational adaptation",
        "int.services.card4.title": "Multicultural Team Coordination",
        "int.services.card4.desc": "Management and support to facilitate global communication and collaboration.",
        "int.services.card4.b1": "• Meeting facilitation",
        "int.services.card4.b2": "• Conflict resolution",
        "int.services.card4.b3": "• Creation of inclusive environments",
        "int.services.card4.b4": "• Intercultural coaching",
        "int.services.card5.title": "International Benchmarking",
        "int.services.card5.desc": "Comparative analysis of global best practices for local adaptation.",
        "int.services.card5.b1": "• Competitor analysis",
        "int.services.card5.b2": "• Best practice studies",
        "int.services.card5.b3": "• Model adaptation",
        "int.services.card5.b4": "• Strategic reports",
        "int.services.card6.title": "Integral Solution",
        "int.services.card6.desc": "Combine multiple services for a complete transformation of your international expansion.",
        "int.services.card6.cta": "Consult Full Package",
        "int.cases.title": "Success Cases with GPMF",
        "int.cases.subtitle": "Discover how we have transformed problems into opportunities for our clients",
        "int.cases.1.title": "Casa Normandía",
        "int.cases.1.subtitle": "International Market Entry Strategy",
        "int.cases.1.desc": "We designed a market entry strategy with short-cycle pilots to learn, adjust, and scale quickly, generating 'quick wins' and an expansion roadmap.",
        "int.cases.1.b1": "Complete internationalization strategy",
        "int.cases.1.b2": "Short-cycle pilots and quick adjustments",
        "int.cases.1.b3": "Clear expansion roadmap",
        "int.cases.2.title": "German-Colombian Scientific Institute",
        "int.cases.2.subtitle": "Strategic Alliance Development",
        "int.cases.2.desc": "A German-Colombian scientific institute was supported to design and execute an alliance strategy that generated sustained growth of over 10% annually.",
        "int.cases.2.b1": "Fund management over €500,000",
        "int.cases.2.b2": "Annual growth exceeding 10%",
        "int.cases.2.b3": "Network of 15+ strategic allies",
        "int.relations.title": "International and Intercultural Relations",
        "int.relations.subtitle": "We build bridges between cultures and markets, transforming diversity into a competitive advantage",
        "int.relations.c1.title": "Global Connections",
        "int.relations.c1.desc": "We facilitate strategic alliances between companies from different continents and cultures.",
        "int.relations.c2.title": "Diverse Teams",
        "int.relations.c2.desc": "We develop intercultural competencies for high-performance multicultural teams.",
        "int.relations.c3.title": "Sustainable Expansion",
        "int.relations.c3.desc": "We design market entry strategies that ensure long-term sustainable growth.",
        "int.pain.title": "Does Your Company Face These Challenges?",
        "int.pain.subtitle": "We understand your pain points and have designed specific solutions for each obstacle",
        "int.pain.c1.title": "Expansion without Strategy",
        "int.pain.c1.desc": "Is your company looking to expand internationally but lacks contacts or a clear strategy?",
        "int.pain.c2.title": "Cultural Barriers",
        "int.pain.c2.desc": "Do you need to establish strategic alliances but face cultural or regulatory barriers?",
        "int.pain.c3.title": "Risky Soft Landing",
        "int.pain.c3.desc": "Are you worried about entering new markets without adequate cultural and logistical preparation?",
        "int.pain.c4.title": "Inefficient Funding",
        "int.pain.c4.desc": "Do your international funding initiatives lack strategic design to access co-financing funds?",
        "int.pain.c5.title": "Intercultural Competencies",
        "int.pain.c5.desc": "Does your team need to strengthen its intercultural competencies to operate effectively globally?",
        "int.pain.c6.title": "Insufficient Analysis",
        "int.pain.c6.desc": "Do you take expansion decisions based on intuition instead of data and contextual analysis?",
        "int.cta.title": "Take the First Step",
        "int.cta.desc": "Don't wait for the competition to get ahead. Our initial diagnostic is the fastest way to get a clear action plan and start transforming your business globally.",
        "int.cta.btn": "I Want My Free Strategic Diagnostic!",
        "int.cta.list_title": "Complete the form and you will receive:",
        "int.cta.list.1": "Free analysis of your internationalization potential",
        "int.cta.list.2": "Personalized recommendations in 48 hours",
        "int.cta.list.3": "Initial roadmap for your global expansion",
    },
    de: {
        "nav.home": "Startseite",
        "nav.firm": "Firma",
        "nav.services": "Dienstleistungen",
        "nav.contact": "Buchen",
        "nav.int": "Internationalisierung",
        "nav.data": "Daten & KI",
        "nav.ai": "KI & Analytik",
        "nav.bizdev": "Expansion & Branchenlösungen",
        "nav.partners": "Partner",
        "nav.team": "Team",

        "home.hero.title": "Globale Komplexität meistern durch",
        "home.hero.span": "strategische Intelligenz.",
        "home.hero.desc": "Wir unterstützen Organisationen dabei, in komplexen Ökosystemen erfolgreich zu sein.",
        "home.hero.cta": "Strategie besprechen",
        "home.hero.services": "Dienstleistungen",
        "home.trust.title": "Vertrauen in globalen Ökosystemen",

        "home.prop.title": "Unser Unterschied",
        "home.prop.1.title": "Globale Verbindung",
        "home.prop.1.desc": "Echte Brücken zwischen LatAm und Europa.",
        "home.prop.2.title": "Kollaborativer Ansatz",
        "home.prop.2.desc": "Wir schaffen Lösungen gemeinsam.",
        "home.prop.3.title": "Kontinuierliche Innovation",
        "home.prop.3.desc": "La technologie au service de la stratégie.",

        "home.areas.title": "Kompetenzfelder",
        "home.areas.desc": "Strategie, Datenmanagement und interdisziplinäre Ausbildung.",
        "home.services.card1.title": "Internationalisierung",
        "home.services.card1.desc": "Expansion mit interkulturellem Fokus. Von Benchmarking bis zum operativen Softlanding.",
        "home.services.card1.bullet1": "Strategische Allianzen",
        "home.services.card1.bullet2": "Handelsmissionen",
        "home.services.card2.title": "Data Governance",
        "home.services.card2.desc": "Wir verwandeln verstreute Daten in strategische Assets für fundierte Entscheidungen.",
        "home.services.card2.bullet1": "Reifegrad-Diagnose",
        "home.services.card2.bullet2": "Datenarchitektur",
        "home.services.card3.title": "Interkulturelles Management",
        "home.services.card3.desc": "Stärkung interner Fähigkeiten, Leadership und Organisationskultur.",
        "home.services.card3.bullet1": "Team-Trainings",
        "home.services.card3.bullet2": "Strategische Planung",
        "home.services.card4.title": "Expansion & Branchenlösungen",
        "home.services.card4.desc": "Expansion, Allianzen und maßgeschneiderte Plays für Agro-Tech, Wissenschaft und Bauwesen.",
        "home.services.card4.bullet1": "Opportunity-Diagnose & globaler Fahrplan",
        "home.services.card4.bullet2": "Partnerschaftsaktivierung & Deal-Support",
        "common.viewDetails": "Details ansehen →",

        "home.why.title": "Keine Standardantworten.",
        "home.why.span": "Wir schaffen Lösungen.",
        "home.why.desc": "Der Wert liegt nicht in den Daten, sondern in der Fähigkeit, sie in Handlungen umzusetzen.",
        "home.why.pillar1.title": "Methodische Strenge",
        "home.why.pillar1.desc": "Standardisierte Prozesse, validiert in Europa und LatAm.",
        "home.why.pillar2.title": "Boutique-Agilität",
        "home.why.pillar2.desc": "Direkter Senior-Partner-Fokus, keine Bürokratie.",
        "home.why.pillar3.title": "Globale Vision",
        "home.why.pillar3.desc": "Trilinguales, multikulturelles ADN.",
        "home.testimonial.quote": "GPMF verstand unsere technische Komplexität und übersetzte sie in eine klare, ausführbare Expansionsstrategie. Sie lieferten nicht nur einen Plan, sie halfen uns auch bei der Umsetzung.",
        "home.testimonial.person": "David A. Rachid",
        "home.testimonial.role": "CEO, DCR Exponential (USA)",
        "home.cta.title": "Bereit, den Standard zu erhöhen.",
        "home.cta.desc": "Buchen Sie ein kostenloses, 30-minütiges Strategiegespräch.",
        "home.cta.btn.primary": "Diagnose anfragen",
        "home.cta.btn.secondary": "Diagnose anfragen",

        "about.hero.title": "Wissenschaft und Strategie.",
        "about.hero.subtitle": "Ohne Grenzen.",
        "about.hero.desc": "GPMF ist eine Mischung aus technischer Strenge und globaler Geschäftsagilität.",
        "about.team.title": "Senior Führung",
        "about.team.desc": "Direkte Betreuung durch Partner.",
        "about.team.adriana.role": "Ingénieurwesen & Komplexität",
        "about.team.adriana.desc": "Ingenieurin mit großer Erfahrung in F&E, öffentlichen Politiken und komplexen Systemen. Bringt Struktur und technische Glaubwürdigkeit.",
        "about.team.marcela.role": "Strategie & Expansion",
        "about.team.marcela.desc": "Experte in Business Development und M&A Sourcing mit trilingualer Sicht. Öffnet anspruchsvolle Märkte und B2B/B2G-Deals.",
        "about.vision.title": "Unser Polarstern",
        "about.vision.desc": "Bis 2030 werden wir die Referenz-Boutique sein, die LatAm, Europa und Nordamerika verbindet.",
        "about.vision.quote": "Bis 2030 sind wir die Boutique-Referenz zwischen Lateinamerika, Europa und Nordamerika, transformieren die Vielfalt und machen sie zur größten Stärke unserer Kunden.",
        "about.vision.stat1": "Kontinente",
        "about.vision.stat2": "Jahre gemeinsame Erfahrung",
        "about.vision.stat3": "Senior-Betreuung",

        "allies.hero.kicker": "Globales Netzwerk",
        "allies.hero.title": "Menschen und Firmen, die unseren Impact verstärken",
        "allies.hero.desc": "Wir vereinen Senior Leadership, Spezialisten und institutionelle Partner in Europa, Nordamerika und Lateinamerika für komplexe Projekte.",
        "allies.core.kicker": "Core Team",
        "allies.core.title": "Partnerinnen und Praxisdirektoren",
        "allies.core.subtitle": "Direkte Betreuung, ohne Junior-Zwischenschritte",
        "allies.core.marcela.role": "Network Management",
        "allies.core.marcela.desc": "Digitale Transformation und Geschäftsausbau in trilingualen ES/EN/DE-Ökosystemen.",
        "allies.core.adriana.role": "Innovation & öffentliche Politik",
        "allies.core.adriana.desc": "Ingenieurin und Strategin für Wissenschaft, Agro und Competitive Intelligence für Regierungen und Multilaterale.",
        "allies.core.natalia.role": "Analyse & Operationen",
        "allies.core.natalia.desc": "Design interner Abläufe und angewandte Analytik für Skalierung.",
        "allies.core.carlos.role": "Business Intelligence & KI",
        "allies.core.carlos.desc": "12+ Jahre BI, Datenstrategie und KI-Rollouts zwischen LatAm und Europa.",
        "allies.partners.kicker": "Partnerschaften",
        "allies.partners.title": "Partnerfirmen und Verbündete",
        "allies.partners.subtitle": "Spezialisierte Zellen je nach Projekt",
        "allies.partner.atelier.desc": "Think Tank für Energiewende, Klimadiplomatie und grüne Finanzierung.",
        "allies.partner.atelier.point1": "• Net-Zero-Fahrpläne",
        "allies.partner.atelier.point2": "• Koordination mit EU-Institutionen",
        "allies.partner.nordic.desc": "Boutique-Studio für legale und kommerzielle Softlanding von Tech-Scaleups.",
        "allies.partner.nordic.point1": "• EU-Gesellschaftsstruktur",
        "allies.partner.nordic.point2": "• Zugang zu Fonds und Digital-Hubs",
        "allies.partner.agro.desc": "Expertennetz für Bioökonomie, Agrotech und Technologietransfer.",
        "allies.partner.agro.point1": "• Internationale Kooperationsprojekte",
        "allies.partner.agro.point2": "• Sektorale Competitive Intelligence",
        "allies.partner.lumen.desc": "KI-Labor für Retail, Gesundheit und Advanced Manufacturing.",
        "allies.partner.lumen.point1": "• Entwicklung prädiktiver Modelle",
        "allies.partner.lumen.point2": "• Integration mehrerer Datenquellen",
        "allies.partner.andino.desc": "Kollektiv ehemaliger Diplomaten und B2G-Verhandler für Infrastrukturprojekte.",
        "allies.partner.andino.point1": "• Institutionelle Beziehungen",
        "allies.partner.andino.point2": "• Regulatorisches Management",
        "allies.partner.humboldt.desc": "Akademisches Spin-off, das DACH-Universitäten mit LATAM-Startups verbindet.",
        "allies.partner.humboldt.point1": "• Open-Innovation-Programme",
        "allies.partner.humboldt.point2": "• Technologietransfer",
        "allies.cta.kicker": "Erweiterte Zusammenarbeit",
        "allies.cta.title": "Ein lebendiges Netzwerk für Hochrisiko-/High-Impact-Projekte.",
        "allies.cta.desc": "Wir aktivieren Squads nach Bedarf: Data Scientists, Rechtsexperten, Wissenschaftsdiplomaten, strategische Storyteller.",
        "allies.cta.point1": "Teams in drei Zeitzonen koordiniert.",
        "allies.cta.point2": "Flexible Verträge: Pod, Retainer oder Sprint.",
        "allies.cta.point3": "Due diligence culturelle et technique avant chaque partenariat.",
        "allies.cta.join.title": "Möchten Sie Partner werden?",
        "allies.cta.join.desc": "Wir suchen Boutique-Firmen mit Ergebnisfokus. Wissenschaft, Technologie, Daten, Diplomatie, Expansion.",
        "allies.cta.join.btn.primary": "Partnerschaft anfragen",
        "allies.cta.join.btn.secondary": "Gespräch vereinbaren",

        // CONTACT
        "contact.sidebar.title": "Lassen Sie uns sprechen",
        "contact.sidebar.desc": "Wir sind bereit, Ihre Herausforderungen zu hören und zu zeigen, wie unser globales Netzwerk Ergebnisse beschleunigt.",
        "contact.sidebar.email.label": "E-Mail",
        "contact.sidebar.email.value": "contacto.gpmfsas@gmail.com",
        "contact.sidebar.location.label": "Standort",
        "contact.sidebar.location.city": "Bogotá, Kolumbien",
        "contact.sidebar.location.note": "Globale Operationen",
        "contact.form.title": "Senden Sie uns eine Nachricht",
        "contact.form.name": "Name",
        "contact.form.placeholder.name": "Ihr Name",
        "contact.form.company": "Unternehmen",
        "contact.form.placeholder.company": "Ihre Organisation",
        "contact.form.email": "Geschäftliche E-Mail",
        "contact.form.placeholder.email": "beispiel@firma.com",
        "contact.form.message": "Nachricht",
        "contact.form.placeholder.message": "Wie können wir helfen?",
        "contact.form.submit": "Nachricht senden",
        "nav.contact": "Buchen",

        // COOKIES
        "cookie.text": "Wir verwenden Cookies.",
        "cookie.btn": "Akzeptieren",

        // SERVICES - INTERNATIONALIZATION
        "int.hero.title1": "Erweitern Sie Ihr Geschäft weltweit:",
        "int.hero.title2": "Strategische Internationalisierung",
        "int.hero.title3": "und Allianzen mit Zweck",
        "int.hero.desc": "Bei GPMF sind wir Ihr strategischer Partner, um internationale Märkte zu navigieren, solide Allianzen aufzubauen und einen erfolgreichen Markteintritt (Soft Landing) in Europa und Lateinamerika zu sichern, wobei kulturelle Herausforderungen in dauerhafte Wettbewerbsvorteile umgewandelt werden.",
        "int.hero.cta": "Fordern Sie Ihre kostenlose strategische Diagnose an",
        "int.method.title": "Bewährte und ergebnisorientierte Methodik",
        "int.method.desc": "Bei GPMF gehen wir über die Theorie hinaus. Wir helfen Ihnen, echten und messbaren Wert zu schaffen, indem wir Analytik und KI in den Mittelpunkt Ihrer Strategie und operativen Effizienz stellen.",
        "int.method.step1.title": "Rigorose Analyse",
        "int.method.step1.desc": "Unsere Methodik kombiniert rigorose Analyse, kontextuelle Intelligenz und die Erleichterung wichtiger Allianzen, um solide und nachhaltige Vorschläge zu erstellen.",
        "int.method.step2.title": "Backward Planning",
        "int.method.step2.desc": "Rückwärtsplanung zur Definition klarer langfristiger Ziele und zur Festlegung der technologischen und organisatorischen Schritte.",
        "int.method.step3.title": "Forward Planning",
        "int.method.step3.desc": "Wir entwerfen eine Markteintrittsstrategie mit Pilotprojekten in kurzen Zyklen, um schnell zu lernen, anzupassen und zu skalieren, wodurch 'schnelle Gewinne' und ein Expansionsfahrplan generiert werden.",
        "int.focus.title": "Unser besonderer Fokus",
        "int.focus.1.bold": "Global und interdisziplinär:",
        "int.focus.1.text": "Wir kombinieren internationale Expertise mit tiefem Branchenwissen",
        "int.focus.2.bold": "Interkultureller Fokus:",
        "int.focus.2.text": "Wir verwandeln kulturelle Barrieren in Wettbewerbsvorteile",
        "int.focus.3.bold": "Datengetrieben:",
        "int.focus.3.text": "Entscheidungen basierend auf fortschrittlicher Analytik und künstlicher Intelligenz",
        "int.focus.4.bold": "Messbare Ergebnisse:",
        "int.focus.4.text": "Jede Initiative hat klare KPIs und kontinuierliches Monitoring",
        "int.services.title": "Unsere Schlüsseldienstleistungen",
        "int.services.subtitle": "Umfassende Lösungen für Ihre Internationalisierung und Entwicklung strategischer Allianzen",
        "int.services.card1.title": "Geschäftsentwicklung und strategische Allianzen",
        "int.services.card1.desc": "Hilft bei der Identifizierung von Wachstumschancen und dem Aufbau strategischer Allianzen in globalen Märkten.",
        "int.services.card1.b1": "• Kompetenzdiagnose",
        "int.services.card1.b2": "• Strategisches Stakeholder-Mapping",
        "int.services.card1.b3": "• Design kollaborativer Vorschläge",
        "int.services.card1.b4": "• Verhandlungsmoderation",
        "int.services.card2.title": "Strategisches Design für Matching Funds",
        "int.services.card2.desc": "Unterstützung zur Erweiterung von Wirkung und Finanzierung durch Zugang zu Kofinanzierungsfonds.",
        "int.services.card2.b1": "• Identifizierung von Möglichkeiten",
        "int.services.card2.b2": "• Formulierung abgestimmter Vorschläge",
        "int.services.card2.b3": "• Integration strategischer Allianzen",
        "int.services.card2.b4": "• Verwaltung europäischer Fonds",
        "int.services.card3.title": "Entwicklung interkultureller Fähigkeiten",
        "int.services.card3.desc": "Schulungsprogramme zur Stärkung der Kompetenzen in multikulturellen Teams.",
        "int.services.card3.b1": "• Interkulturelle Kommunikation",
        "int.services.card3.b2": "• Management diverser Teams",
        "int.services.card3.b3": "• Interkulturelle Verhandlung",
        "int.services.card3.b4": "• Organisatorische Anpassung",
        "int.services.card4.title": "Koordination multikultureller Teams",
        "int.services.card4.desc": "Management und Begleitung zur Erleichterung globaler Kommunikation und Zusammenarbeit.",
        "int.services.card4.b1": "• Moderation von Besprechungen",
        "int.services.card4.b2": "• Konfliktlösung",
        "int.services.card4.b3": "• Schaffung inklusiver Umgebungen",
        "int.services.card4.b4": "• Interkulturelles Coaching",
        "int.services.card5.title": "Internationales Benchmarking",
        "int.services.card5.desc": "Vergleichende Analyse globaler Best Practices zur lokalen Anpassung.",
        "int.services.card5.b1": "• Wettbewerberanalyse",
        "int.services.card5.b2": "• Studien zu Best Practices",
        "int.services.card5.b3": "• Anpassung von Modellen",
        "int.services.card5.b4": "• Strategische Berichte",
        "int.services.card6.title": "Ganzheitliche Lösung",
        "int.services.card6.desc": "Kombinieren Sie mehrere Dienstleistungen für eine vollständige Transformation Ihrer internationalen Expansion.",
        "int.services.card6.cta": "Komplettpaket anfragen",
        "int.cases.title": "Erfolgsgeschichten mit GPMF",
        "int.cases.subtitle": "Entdecken Sie, wie wir Probleme in Chancen für unsere Kunden verwandelt haben",
        "int.cases.1.title": "Casa Normandía",
        "int.cases.1.subtitle": "Markteintrittsstrategie international",
        "int.cases.1.desc": "Wir entwarfen eine Markteintrittsstrategie mit Pilotprojekten in kurzen Zyklen, um schnell zu lernen, anzupassen und zu skalieren, wodurch 'schnelle Gewinne' und ein Expansionsfahrplan generiert wurden.",
        "int.cases.1.b1": "Vollständige Internationalisierungsstrategie",
        "int.cases.1.b2": "Kurzzyklische Pilotprojekte und schnelle Anpassungen",
        "int.cases.1.b3": "Klarer Expansionsfahrplan",
        "int.cases.2.title": "Deutsch-Kolumbianisches Wissenschaftsinstitut",
        "int.cases.2.subtitle": "Entwickl. strategischer Allianzen",
        "int.cases.2.desc": "Ein deutsch-kolumbianisches Wissenschaftsinstitut wurde dabei unterstützt, eine Allianzstrategie zu entwerfen und umzusetzen, die ein nachhaltiges Wachstum von über 10% jährlich generierte.",
        "int.cases.2.b1": "Fondsmanagement über 500.000 €",
        "int.cases.2.b2": "Jährliches Wachstum über 10%",
        "int.cases.2.b3": "Netzwerk von 15+ strategischen Partnern",
        "int.relations.title": "Internationale und interkulturelle Beziehungen",
        "int.relations.subtitle": "Wir bauen Brücken zwischen Kulturen und Märkten und verwandeln Vielfalt in einen Wettbewerbsvorteil",
        "int.relations.c1.title": "Globale Verbindungen",
        "int.relations.c1.desc": "Wir erleichtern strategische Allianzen zwischen Unternehmen verschiedener Kontinente und Kulturen.",
        "int.relations.c2.title": "Diverse Teams",
        "int.relations.c2.desc": "Wir entwickeln interkulturelle Kompetenzen für multikulturelle Hochleistungsteams.",
        "int.relations.c3.title": "Nachhaltige Expansion",
        "int.relations.c3.desc": "Wir entwerfen Markteintrittsstrategien, die langfristig nachhaltiges Wachstum sichern.",
        "int.pain.title": "Steht Ihr Unternehmen vor diesen Herausforderungen?",
        "int.pain.subtitle": "Wir verstehen Ihre 'Schmerzpunkte' und haben spezifische Lösungen für jedes Hindernis entwickelt",
        "int.pain.c1.title": "Expansion ohne Strategie",
        "int.pain.c1.desc": "Möchte Ihr Unternehmen international expandieren, aber es fehlen Kontakte oder eine klare Strategie?",
        "int.pain.c2.title": "Kulturelle Barrieren",
        "int.pain.c2.desc": "Müssen Sie strategische Allianzen aufbauen, stoßen aber auf kulturelle oder normative Barrieren?",
        "int.pain.c3.title": "Risiko Soft Landing",
        "int.pain.c3.desc": "Sorgen Sie sich um den Eintritt in neue Märkte ohne angemessene kulturelle und logistische Vorbereitung?",
        "int.pain.c4.title": "Ineffiziente Finanzierung",
        "int.pain.c4.desc": "Fehlt Ihren internationalen Finanzierungsinitiativen das strategische Design für den Zugang zu Kofinanzierungsfonds?",
        "int.pain.c5.title": "Interkulturelle Kompetenzen",
        "int.pain.c5.desc": "Muss Ihr Team seine interkulturellen Kompetenzen stärken, um global effektiv zu agieren?",
        "int.pain.c6.title": "Unzureichende Analyse",
        "int.pain.c6.desc": "Treffen Sie Expansionsentscheidungen basierend auf Intuition statt auf Daten und Kontextanalyse?",
        "int.cta.title": "Machen Sie den ersten Schritt",
        "int.cta.desc": "Warten Sie nicht, bis die Konkurrenz Sie überholt. Unsere erste Diagnose ist der schnellste Weg, um einen klaren Aktionsplan zu erhalten und Ihr Geschäft global zu transformieren.",
        "int.cta.btn": "Ich möchte meine kostenlose strategische Diagnose!",
        "int.cta.list_title": "Füllen Sie das Formular aus und Sie erhalten:",
        "int.cta.list.1": "Kostenlose Analyse Ihres Internationalisierungspotenzials",
        "int.cta.list.2": "Personalisierte Empfehlungen in 48 Stunden",
        "int.cta.list.3": "Erster Fahrplan für Ihre globale Expansion",
    },
    fr: {
        "nav.home": "Accueil",
        "nav.firm": "Cabinet",
        "nav.services": "Services",
        "nav.contact": "Réserver",
        "nav.int": "Internationalisation",
        "nav.data": "Données et IA",
        "nav.ai": "IA & Analytique",
        "nav.bizdev": "Expansion & Solutions Sectorielles",
        "nav.partners": "Alliés",
        "nav.team": "Équipe",

        "home.hero.title": "Naviguer dans la complexité grâce à",
        "home.hero.span": "l'intelligence stratégique.",
        "home.hero.desc": "Nous aidons les organisations à prospérer dans des écosystèmes complexes.",
        "home.hero.cta": "Parlons Stratégie",
        "home.hero.services": "Explorer les Services",
        "home.trust.title": "Confiance générée dans des écosystèmes mondiaux",

        "home.prop.title": "Notre Différence",
        "home.prop.1.title": "Connexion Mondiale",
        "home.prop.1.desc": "De véritables ponts entre l'Amérique latine et l'Europe.",
        "home.prop.2.title": "Approche Collaborative",
        "home.prop.2.desc": "Nous co-créons des solutions.",
        "home.prop.3.title": "Innovation Continue",
        "home.prop.3.desc": "La technologie au service de la stratégie.",

        "home.areas.title": "Domaines d'Expertise",
        "home.areas.desc": "Stratégie, gestion intelligente des données et formation interdisciplinaire.",
        "home.services.card1.title": "Internationalisation",
        "home.services.card1.desc": "Expansion à focale interculturelle. Du benchmarking au softlanding opérationnel.",
        "home.services.card1.bullet1": "Alliances stratégiques",
        "home.services.card1.bullet2": "Missions commerciales",
        "home.services.card2.title": "Gouvernance des Données",
        "home.services.card2.desc": "Nous transformons des données dispersées en actifs stratégiques pour des décisions éclairées.",
        "home.services.card2.bullet1": "Diagnostic de maturité",
        "home.services.card2.bullet2": "Architecture de données",
        "home.services.card3.title": "Gestion Interculturelle",
        "home.services.card3.desc": "Renforcement des capacités internes, du leadership et de la culture organisationnelle.",
        "home.services.card3.bullet1": "Formation des équipes",
        "home.services.card3.bullet2": "Planification stratégique",
        "home.services.card4.title": "Expansion & Solutions Sectorielles",
        "home.services.card4.desc": "Expansion, alliances et solutions sur mesure pour l’Agro-Tech, la science et la construction.",
        "home.services.card4.bullet1": "Diagnostic d’opportunité & feuille de route",
        "home.services.card4.bullet2": "Activation de partenariats & closing",
        "common.viewDetails": "Voir détails →",

        "home.why.title": "Pas de réponses toutes faites.",
        "home.why.span": "Nous co-créons des solutions.",
        "home.why.desc": "La valeur réside dans la capacité à transformer les données en action.",
        "home.why.pillar1.title": "Rigueur Méthodologique",
        "home.why.pillar1.desc": "Processus standardisés validés en Europe et en Amérique latine.",
        "home.why.pillar2.title": "Agilité Boutique",
        "home.why.pillar2.desc": "Attention directe des associés seniors, sans bureaucratie.",
        "home.why.pillar3.title": "Vision Globale",
        "home.why.pillar3.desc": "ADN trilingue et multiculturel natif.",
        "home.testimonial.quote": "GPMF a compris notre complexité technique et l'a traduite en une stratégie d'expansion claire et exécutable. Ils nous ont aidés à construire la capacité d'exécution.",
        "home.testimonial.person": "David A. Rachid",
        "home.testimonial.role": "CEO, DCR Exponential (USA)",
        "home.cta.title": "Prêt à élever le standard.",
        "home.cta.desc": "Planifiez une session de diagnostic stratégique de 30 minutes offerte.",
        "home.cta.btn.primary": "Demander un diagnostic",
        "home.cta.btn.secondary": "Solicitar Diagnóstico",

        "about.hero.title": "Science et Stratégie.",
        "about.hero.subtitle": "Sans frontières.",
        "about.hero.desc": "GPMF est un hybride entre la rigueur de l'ingénierie et l'agilité des affaires mondiales.",
        "about.team.title": "Direction Senior",
        "about.team.desc": "Attention directe des associés.",
        "about.team.adriana.role": "Ingénierie & Complexité",
        "about.team.adriana.desc": "Ingénieure avec une large expérience en R&D, politiques publiques et systèmes complexes. Apporte structure et crédibilité technique.",
        "about.team.marcela.role": "Stratégie & Expansion",
        "about.team.marcela.desc": "Experte en développement des affaires et sourcing M&A, vision trilingue. Ouvre des marchés difficiles et négociations B2B/B2G.",
        "about.vision.title": "Notre Étoile Polaire",
        "about.vision.desc": "D'ici 2030, nous serons le cabinet de référence reliant l'Amérique latine, l'Europe et l'Amérique du Nord.",
        "about.vision.quote": "D'ici 2030, nous serons la boutique de référence reliant l'Amérique latine, l'Europe et l'Amérique du Nord, transformant la diversité culturelle et technologique en avantage compétitif.",
        "about.vision.stat1": "Continents",
        "about.vision.stat2": "Années d'expérience",
        "about.vision.stat3": "Attention senior",

        "allies.hero.kicker": "Réseau Global",
        "allies.hero.title": "Des personnes et des firmes qui amplifient notre impact",
        "allies.hero.desc": "Nous réunissons leadership senior, stratèges spécialisés et alliés institutionnels entre Europe, Amérique du Nord et Amérique latine pour débloquer des projets complexes.",
        "allies.core.kicker": "Core Team",
        "allies.core.title": "Associées et directeurs de pratique",
        "allies.core.subtitle": "Attention directe, sans intermédiaires juniors",
        "allies.core.marcela.role": "Network Management",
        "allies.core.marcela.desc": "Transformation digitale et expansion commerciale dans des écosystèmes trilingues ES/EN/DE.",
        "allies.core.adriana.role": "Innovation & Politiques Publiques",
        "allies.core.adriana.desc": "Ingénieure et stratégiste en science, agro et intelligence concurrentielle pour gouvernements et multilatéraux.",
        "allies.core.natalia.role": "Analyse & Opérations",
        "allies.core.natalia.desc": "Conception des opérations internes et analytique appliquée pour la scalabilité.",
        "allies.core.carlos.role": "Business Intelligence & IA",
        "allies.core.carlos.desc": "12+ ans en BI, stratégie data et déploiements IA entre LatAm et Europe.",
        "allies.partners.kicker": "Alliances",
        "allies.partners.title": "Partenaires et firmes associées",
        "allies.partners.subtitle": "Cellules spécialisées que nous mobilisons selon le projet",
        "allies.partner.atelier.desc": "Think tank sur la transition énergétique, la diplomatie climatique et le financement vert.",
        "allies.partner.atelier.point1": "• Conception de feuilles de route Net-Zero",
        "allies.partner.atelier.point2": "• Coordination avec les institutions de l'UE",
        "allies.partner.nordic.desc": "Studio boutique pour softlanding juridique et commercial des scaleups tech.",
        "allies.partner.nordic.point1": "• Structuration juridique dans l'UE",
        "allies.partner.nordic.point2": "• Accès à des fonds et hubs digitaux",
        "allies.partner.agro.desc": "Réseau d'experts en bioéconomie, agrotech et transfert technologique.",
        "allies.partner.agro.point1": "• Projets de coopération internationale",
        "allies.partner.agro.point2": "• Intelligence concurrentielle sectorielle",
        "allies.partner.lumen.desc": "Laboratoire d'IA appliquée pour le retail, la santé et l'industrie avancée.",
        "allies.partner.lumen.point1": "• Développement de modèles prédictifs",
        "allies.partner.lumen.point2": "• Intégration de données multi-sources",
        "allies.partner.andino.desc": "Collectif d'anciens diplomates et négociateurs B2G pour les projets d'infrastructure.",
        "allies.partner.andino.point1": "• Relations institutionnelles",
        "allies.partner.andino.point2": "• Gestion réglementaire",
        "allies.partner.humboldt.desc": "Spin-off académique reliant les universités DACH aux startups latino-américaines.",
        "allies.partner.humboldt.point1": "• Programmes d'innovation ouverte",
        "allies.partner.humboldt.point2": "• Transfert technologique",
        "allies.cta.kicker": "Collaboration étendue",
        "allies.cta.title": "Un réseau vivant pour des projets à haut risque et haut impact.",
        "allies.cta.desc": "Nous activons des squads selon le défi : data scientists, juristes, diplomates scientifiques, storytellers stratégiques.",
        "allies.cta.point1": "Équipes transnationales coordonnées sur trois fuseaux horaires.",
        "allies.cta.point2": "Contrats flexibles : pod, retainer ou accélération par sprint.",
        "allies.cta.point3": "Due diligence culturelle et technique avant chaque partenariat.",
        "allies.cta.join.title": "Envie de rejoindre l'alliance ?",
        "allies.cta.join.desc": "Nous recherchons des firmes boutique orientées résultats. Science, technologie, data, diplomatie, expansion.",
        "allies.cta.join.btn.primary": "Proposer une alliance",
        "allies.cta.join.btn.secondary": "Planifier un échange",

        // CONTACT
        "contact.sidebar.title": "Discutons",
        "contact.sidebar.desc": "Nous sommes prêts à écouter vos défis et à activer notre réseau mondial pour accélérer vos résultats.",
        "contact.sidebar.email.label": "Email",
        "contact.sidebar.email.value": "contacto.gpmfsas@gmail.com",
        "contact.sidebar.location.label": "Localisation",
        "contact.sidebar.location.city": "Bogotá, Colombie",
        "contact.sidebar.location.note": "Opérations globales",
        "contact.form.title": "Envoyez-nous un message",
        "contact.form.name": "Nom",
        "contact.form.placeholder.name": "Votre nom",
        "contact.form.company": "Entreprise",
        "contact.form.placeholder.company": "Votre organisation",
        "contact.form.email": "Email professionnel",
        "contact.form.placeholder.email": "exemple@entreprise.com",
        "contact.form.message": "Message",
        "contact.form.placeholder.message": "Comment pouvons-nous vous aider ?",
        "contact.form.submit": "Envoyer",

        "cookie.text": "Nous utilisons des cookies.",
        "cookie.btn": "Accepter",

        // SERVICES - INTERNATIONALISATION
        "int.hero.title1": "Développez votre entreprise à l'échelle mondiale :",
        "int.hero.title2": "Internationalisation Stratégique",
        "int.hero.title3": "et Alliances avec un But",
        "int.hero.desc": "Chez GPMF, nous sommes votre partenaire stratégique pour naviguer sur les marchés internationaux, construire des alliances solides et assurer une entrée réussie (soft landing) en Europe et en Amérique latine, transformant les défis culturels en avantages concurrentiels durables.",
        "int.hero.cta": "Demandez votre Diagnostic Stratégique Gratuit",
        "int.method.title": "Méthodologie Éprouvée et Orientée Résultats",
        "int.method.desc": "Chez GPMF, nous allons au-delà de la théorie. Nous vous aidons à générer une valeur réelle et mesurable, en faisant de l'analytique et de l'IA le cœur de votre stratégie et de votre efficacité opérationnelle.",
        "int.method.step1.title": "Analyse Rigoureuse",
        "int.method.step1.desc": "Notre méthodologie combine une analyse rigoureuse, une intelligence contextuelle et la facilitation d'alliances clés pour construire des propositions solides et durables.",
        "int.method.step2.title": "Planification à Rebours",
        "int.method.step2.desc": "Planification à rebours pour définir des objectifs clairs à long terme et tracer les étapes technologiques et organisationnelles.",
        "int.method.step3.title": "Planification Prospective",
        "int.method.step3.desc": "Nous concevons une stratégie d'entrée sur le marché avec des pilotes en cycles courts pour apprendre, ajuster et évoluer rapidement, générant des « victoires rapides » et une feuille de route d'expansion.",
        "int.focus.title": "Notre Approche Distinctive",
        "int.focus.1.bold": "Globale et Interdisciplinaire :",
        "int.focus.1.text": "Nous combinons expertise internationale et connaissance sectorielle approfondie",
        "int.focus.2.bold": "Approche Interculturelle :",
        "int.focus.2.text": "Nous transformons les barrières culturelles en avantages concurrentiels",
        "int.focus.3.bold": "Impulsion par les Données :",
        "int.focus.3.text": "Décisions basées sur l'analytique avancée et l'intelligence artificielle",
        "int.focus.4.bold": "Résultats Mesurables :",
        "int.focus.4.text": "Chaque initiative a des KPI clairs et un suivi continu",
        "int.services.title": "Nos Services Clés",
        "int.services.subtitle": "Solutions complètes pour votre internationalisation et le développement d'alliances stratégiques",
        "int.services.card1.title": "Développement d'Affaires et Alliances Stratégiques",
        "int.services.card1.desc": "Aide à identifier les opportunités de croissance et à établir des alliances stratégiques sur les marchés mondiaux.",
        "int.services.card1.b1": "• Diagnostic de capacités",
        "int.services.card1.b2": "• Cartographie des acteurs stratégiques",
        "int.services.card1.b3": "• Conception de propositions collaboratives",
        "int.services.card1.b4": "• Facilitation de négociations",
        "int.services.card2.title": "Conception Stratégique pour Fonds de Contrepartie",
        "int.services.card2.desc": "Soutien pour étendre l'impact et le financement grâce à l'accès aux fonds de cofinancement.",
        "int.services.card2.b1": "• Identification d'opportunités",
        "int.services.card2.b2": "• Formulation de propositions alignées",
        "int.services.card2.b3": "• Intégration d'alliances stratégiques",
        "int.services.card2.b4": "• Gestion de fonds européens",
        "int.services.card3.title": "Développement de Compétences Interculturelles",
        "int.services.card3.desc": "Programmes de formation pour renforcer les compétences dans les équipes multiculturelles.",
        "int.services.card3.b1": "• Communication interculturelle",
        "int.services.card3.b2": "• Gestion d'équipes diversifiées",
        "int.services.card3.b3": "• Négociation interculturelle",
        "int.services.card3.b4": "• Adaptation organisationnelle",
        "int.services.card4.title": "Coordination d'Équipes Multiculturelles",
        "int.services.card4.desc": "Gestion et accompagnement pour faciliter la communication et la collaboration mondiale.",
        "int.services.card4.b1": "• Facilitation de réunions",
        "int.services.card4.b2": "• Résolution de conflits",
        "int.services.card4.b3": "• Création d'environnements inclusifs",
        "int.services.card4.b4": "• Coaching interculturel",
        "int.services.card5.title": "Benchmarking International",
        "int.services.card5.desc": "Analyse comparative des meilleures pratiques mondiales pour une adaptation locale.",
        "int.services.card5.b1": "• Analyse des concurrents",
        "int.services.card5.b2": "• Études des meilleures pratiques",
        "int.services.card5.b3": "• Adaptation de modèles",
        "int.services.card5.b4": "• Rapports stratégiques",
        "int.services.card6.title": "Solution Intégrale",
        "int.services.card6.desc": "Combinez plusieurs services pour une transformation complète de votre expansion internationale.",
        "int.services.card6.cta": "Consulter le Forfait Complet",
        "int.cases.title": "Cas de Succès avec GPMF",
        "int.cases.subtitle": "Découvrez comment nous avons transformé les problèmes en opportunités pour nos clients",
        "int.cases.1.title": "Casa Normandía",
        "int.cases.1.subtitle": "Stratégie de Sortie sur le Marché International",
        "int.cases.1.desc": "Nous avons conçu une stratégie de sortie sur le marché avec des pilotes en cycles courts pour apprendre, ajuster et évoluer rapidement, générant des « victoires rapides » et une feuille de route d'expansion.",
        "int.cases.1.b1": "Stratégie d'internationalisation complète",
        "int.cases.1.b2": "Pilotes en cycles courts et ajustements rapides",
        "int.cases.1.b3": "Feuille de route d'expansion claire",
        "int.cases.2.title": "Institut Scientifique Allemand-Colombien",
        "int.cases.2.subtitle": "Dév. d'Alliances Stratégiques",
        "int.cases.2.desc": "Un institut scientifique allemand-colombien a été soutenu pour concevoir et exécuter une stratégie d'alliance qui a généré une croissance soutenue de plus de 10 % par an.",
        "int.cases.2.b1": "Gestion de fonds de plus de 500 000 €",
        "int.cases.2.b2": "Croissance annuelle supérieure à 10 %",
        "int.cases.2.b3": "Réseau de 15+ alliés stratégiques",
        "int.relations.title": "Relations Internationales et Interculturelles",
        "int.relations.subtitle": "Nous construisons des ponts entre les cultures et les marchés, transformant la diversité en avantage concurrentiel",
        "int.relations.c1.title": "Connexions Globales",
        "int.relations.c1.desc": "Nous facilitons les alliances stratégiques entre entreprises de différents continents et cultures.",
        "int.relations.c2.title": "Équipes Diversifiées",
        "int.relations.c2.desc": "Nous développons des compétences interculturelles pour des équipes multiculturelles performantes.",
        "int.relations.c3.title": "Expansion Durable",
        "int.relations.c3.desc": "Nous concevons des stratégies d'entrée sur le marché qui assurent une croissance durable à long terme.",
        "int.pain.title": "Votre Entreprise Rencontre-t-elle Ces Défis ?",
        "int.pain.subtitle": "Nous comprenons vos « points de douleur » et avons conçu des solutions spécifiques pour chaque obstacle",
        "int.pain.c1.title": "Expansion sans Stratégie",
        "int.pain.c1.desc": "Votre entreprise cherche-t-elle à se développer à l'international mais manque de contacts ou de stratégie claire ?",
        "int.pain.c2.title": "Barrières Culturelles",
        "int.pain.c2.desc": "Avez-vous besoin d'établir des alliances stratégiques mais vous heurtez à des barrières culturelles ou normatives ?",
        "int.pain.c3.title": "Soft Landing Risqué",
        "int.pain.c3.desc": "Craignez-vous une entrée sur de nouveaux marchés sans préparation culturelle et logistique adéquate ?",
        "int.pain.c4.title": "Financement Inefficace",
        "int.pain.c4.desc": "Vos initiatives de financement international manquent-elles de conception stratégique pour accéder aux fonds de cofinancement ?",
        "int.pain.c5.title": "Compétences Interculturelles",
        "int.pain.c5.desc": "Votre équipe a-t-elle besoin de renforcer ses compétences interculturelles pour opérer efficacement à l'échelle mondiale ?",
        "int.pain.c6.title": "Analyse Insuffisante",
        "int.pain.c6.desc": "Prenez-vous des décisions d'expansion basées sur l'intuition plutôt que sur des données et une analyse contextuelle ?",
        "int.cta.title": "Faites le Premier Pas",
        "int.cta.desc": "N'attendez pas que la concurrence prenne de l'avance. Notre diagnostic initial est le moyen le plus rapide d'obtenir un plan d'action clair et de commencer à transformer votre entreprise à l'échelle mondiale.",
        "int.cta.btn": "Je Veux Mon Diagnostic Stratégique Gratuit !",
        "int.cta.list_title": "Remplissez le formulaire et vous recevrez :",
        "int.cta.list.1": "Analyse gratuite de votre potentiel d'internationalisation",
        "int.cta.list.2": "Recommandations personnalisées en 48 heures",
        "int.cta.list.3": "Feuille de route initiale pour votre expansion mondiale",
    }
};

function changeLanguage(lang) {
    localStorage.setItem('gpmf-lang', lang);
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[lang][key];
            } else {
                element.textContent = translations[lang][key];
            }
        }
    });
    document.querySelectorAll('.lang-btn').forEach(btn => {
        if (btn.dataset.lang === lang) {
            btn.classList.add('text-burgundy', 'font-bold');
            btn.classList.remove('text-gray-400');
        } else {
            btn.classList.remove('text-burgundy', 'font-bold');
            btn.classList.add('text-gray-400');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('gpmf-lang') || 'es';
    changeLanguage(savedLang);

    const menuBtn = document.getElementById('mobile-menu-btn');
    const mobileMenu = document.getElementById('mobile-menu');
    if (menuBtn && mobileMenu) {
        menuBtn.addEventListener('click', () => {
            mobileMenu.classList.toggle('hidden');
            mobileMenu.classList.toggle('flex');
        });
    }

    document.querySelectorAll('.mobile-services-toggle').forEach(button => {
        const panel = button.nextElementSibling;
        button.addEventListener('click', () => {
            const expanded = button.getAttribute('aria-expanded') === 'true';
            button.setAttribute('aria-expanded', (!expanded).toString());
            if (panel) {
                panel.classList.toggle('hidden');
            }
            const icon = button.querySelector('svg');
            if (icon) {
                icon.classList.toggle('rotate-180');
            }
        });
    });
});

function acceptCookies() {
    localStorage.setItem('gpmf-cookie-consent', 'true');
    document.getElementById('cookie-banner').classList.add('hidden');
}