import type { PlanResponse, MostBoughtPlanData } from "./types";

const defaultBillingType = {
  id: "mock-billing-monthly",
  name: "Monthly",
  description: "Billed every month",
};

export const mockStandardPlans: PlanResponse[] = [
  {
    id: "std-1",
    name: "Essentials",
    subtitle: "Perfect for individuals starting their journey with basic features",
    description: "Basic plan for individuals",
    base_price: 49,
    currency: "USD",
    category: "standard",
    billing_type_id: defaultBillingType.id,
    billing_type: defaultBillingType,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    features: [],
  },
  {
    id: "std-2",
    name: "Professional",
    subtitle: "Best for growing teams with advanced collaboration tools",
    description: "Advanced plan for teams",
    base_price: 129,
    currency: "USD",
    category: "standard",
    billing_type_id: defaultBillingType.id,
    billing_type: defaultBillingType,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    features: [],
  },
  {
    id: "std-3",
    name: "Enterprise",
    subtitle: "Full-featured plan for large organizations with premium support",
    description: "Enterprise-grade plan",
    base_price: 299,
    currency: "USD",
    category: "standard",
    billing_type_id: defaultBillingType.id,
    billing_type: defaultBillingType,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    features: [],
  },
  {
    id: "std-4",
    name: "Executive",
    subtitle: "White-glove service with dedicated account management",
    description: "Premium executive plan",
    base_price: 599,
    currency: "USD",
    category: "standard",
    billing_type_id: defaultBillingType.id,
    billing_type: defaultBillingType,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    features: [],
  },
];

export const mockCustomPlans: PlanResponse[] = [
  {
    id: "cst-1",
    name: "Corporate Wellness",
    subtitle: "Tailored wellness program for corporate teams of 50+",
    description: "Custom corporate wellness plan",
    base_price: 2500,
    currency: "USD",
    category: "custom",
    billing_type_id: defaultBillingType.id,
    billing_type: defaultBillingType,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    features: [],
  },
  {
    id: "cst-2",
    name: "Agency Bundle",
    subtitle: "Multi-client management for consulting agencies",
    description: "Multi-client agency bundle",
    base_price: 1800,
    currency: "USD",
    category: "custom",
    billing_type_id: defaultBillingType.id,
    billing_type: defaultBillingType,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    features: [],
  },
];

export const mockMostBoughtPlan: MostBoughtPlanData = {
  id: "std-2",
  title: "Professional",
  subtitle: "Best for growing teams with advanced collaboration tools",
  price: "$129",
  details: [
    "12 one-on-one sessions per month",
    "Priority scheduling with 24h notice",
    "Access to group workshops (unlimited)",
    "Personalized progress tracking dashboard",
    "Email & chat support within 4 hours",
    "Monthly performance review report",
  ],
  stats: {
    earnings: "$100,000",
    sold: 140,
    conversionRate: "1/9",
    inCart: 20,
  },
};
